import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// 真实 AI 工具数据
const realTools = [
  {
    name: 'ChatGPT',
    slug: 'chatgpt',
    shortDesc: 'OpenAI 开发的 AI 聊天机器人，支持多种对话场景',
    description: 'ChatGPT 是由 OpenAI 开发的大型语言模型，能够进行自然语言对话、回答问题、协助写作、编程等多种任务。支持 GPT-4 和 GPT-3.5 模型。',
    websiteUrl: 'https://chat.openai.com',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    pricingType: 'FREEMIUM',
    tags: '聊天,写作,编程,AI助手',
    stars: 150000,
    upvotes: 25000,
    source: 'manual',
    isFeatured: true,
  },
  {
    name: 'Claude',
    slug: 'claude',
    shortDesc: 'Anthropic 开发的 AI 助手，擅长长文本处理和分析',
    description: 'Claude 是 Anthropic 开发的 AI 助手，以安全性和有用性著称，特别擅长处理长文档和复杂分析任务。支持 100K+ 上下文窗口。',
    websiteUrl: 'https://claude.ai',
    logoUrl: '',
    pricingType: 'FREEMIUM',
    tags: '聊天,分析,长文本,AI助手',
    stars: 45000,
    upvotes: 12000,
    source: 'manual',
    isFeatured: true,
  },
  {
    name: 'Midjourney',
    slug: 'midjourney',
    shortDesc: 'AI 图像生成工具，通过文本描述创建高质量图像',
    description: 'Midjourney 是一个独立的 AI 图像生成服务，用户通过 Discord 机器人与系统交互，生成艺术风格的高质量图像。',
    websiteUrl: 'https://www.midjourney.com',
    logoUrl: '',
    pricingType: 'PAID',
    tags: '图像生成,艺术创作,Discord',
    stars: 85000,
    upvotes: 18000,
    source: 'manual',
    isFeatured: true,
  },
  {
    name: 'Stable Diffusion',
    slug: 'stable-diffusion',
    shortDesc: '开源 AI 图像生成模型，可本地部署',
    description: 'Stable Diffusion 是 Stability AI 开源的文本到图像生成模型，可以在消费级 GPU 上运行，支持本地部署和自定义训练。',
    websiteUrl: 'https://stability.ai',
    githubUrl: 'https://github.com/Stability-AI/stablediffusion',
    logoUrl: '',
    pricingType: 'OPEN_SOURCE',
    tags: '开源,图像生成,本地部署,WebUI',
    stars: 120000,
    upvotes: 22000,
    source: 'manual',
    isFeatured: true,
  },
  {
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    shortDesc: 'AI 编程助手，自动补全代码',
    description: 'GitHub Copilot 是由 GitHub 和 OpenAI 合作开发的 AI 编程助手，能够根据上下文自动补全代码，支持多种编程语言。',
    websiteUrl: 'https://github.com/features/copilot',
    logoUrl: '',
    pricingType: 'PAID',
    tags: '编程,代码补全,IDE插件',
    stars: 95000,
    upvotes: 35000,
    source: 'manual',
    isFeatured: false,
  },
  {
    name: 'Perplexity AI',
    slug: 'perplexity-ai',
    shortDesc: 'AI 搜索引擎，提供带引用的答案',
    description: 'Perplexity AI 是一个 AI 驱动的搜索引擎，能够综合多个来源的信息，提供带引用的直接答案，支持实时信息检索。',
    websiteUrl: 'https://www.perplexity.ai',
    logoUrl: '',
    pricingType: 'FREEMIUM',
    tags: '搜索,问答,研究',
    stars: 28000,
    upvotes: 9500,
    source: 'manual',
    isFeatured: false,
  },
  {
    name: 'Sora',
    slug: 'sora',
    shortDesc: 'OpenAI 视频生成模型，文本生成高质量视频',
    description: 'Sora 是 OpenAI 开发的文本到视频生成模型，能够根据文本描述生成长达一分钟的高质量视频，支持复杂场景和物理模拟。',
    websiteUrl: 'https://openai.com/sora',
    logoUrl: '',
    pricingType: 'PAID',
    tags: '视频生成,OpenAI,Sora',
    stars: 45000,
    upvotes: 18000,
    source: 'manual',
    isFeatured: true,
  },
  {
    name: 'DALL·E 3',
    slug: 'dalle-3',
    shortDesc: 'OpenAI 最新图像生成模型',
    description: 'DALL·E 3 是 OpenAI 开发的第三代文本到图像生成模型，在图像质量和文本理解方面有显著提升，集成在 ChatGPT Plus 中。',
    websiteUrl: 'https://openai.com/dall-e-3',
    logoUrl: '',
    pricingType: 'FREEMIUM',
    tags: '图像生成,OpenAI,艺术创作',
    stars: 65000,
    upvotes: 15000,
    source: 'manual',
    isFeatured: false,
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    shortDesc: 'AI 驱动的代码编辑器',
    description: 'Cursor 是一个基于 VS Code 的 AI 代码编辑器，集成了 GPT-4，支持代码生成、重构和解释，专为提高开发效率设计。',
    websiteUrl: 'https://cursor.sh',
    logoUrl: '',
    pricingType: 'FREEMIUM',
    tags: '编程,IDE,代码生成',
    stars: 32000,
    upvotes: 12000,
    source: 'manual',
    isFeatured: false,
  },
  {
    name: 'ElevenLabs',
    slug: 'elevenlabs',
    shortDesc: 'AI 语音合成和克隆平台',
    description: 'ElevenLabs 提供高质量的 AI 语音合成服务，支持语音克隆、多语言和情感表达，广泛应用于内容创作和配音。',
    websiteUrl: 'https://elevenlabs.io',
    logoUrl: '',
    pricingType: 'FREEMIUM',
    tags: '语音合成,语音克隆,多语言',
    stars: 28000,
    upvotes: 8500,
    source: 'manual',
    isFeatured: false,
  },
  {
    name: 'Runway ML',
    slug: 'runway-ml',
    shortDesc: 'AI 视频编辑和生成平台',
    description: 'Runway ML 提供一系列 AI 视频编辑工具，包括视频生成、背景移除、运动追踪等功能，是创意工作者的强大工具。',
    websiteUrl: 'https://runwayml.com',
    logoUrl: '',
    pricingType: 'FREEMIUM',
    tags: '视频编辑,视频生成,创意工具',
    stars: 25000,
    upvotes: 8000,
    source: 'manual',
    isFeatured: false,
  },
  {
    name: 'Notion AI',
    slug: 'notion-ai',
    shortDesc: 'Notion 内置的 AI 写作助手',
    description: 'Notion AI 集成在 Notion 工作空间中，提供写作辅助、内容总结、头脑风暴等功能，帮助用户提高工作效率。',
    websiteUrl: 'https://www.notion.so/product/ai',
    logoUrl: '',
    pricingType: 'PAID',
    tags: '写作,笔记,生产力',
    stars: 35000,
    upvotes: 15000,
    source: 'manual',
    isFeatured: false,
  },
  {
    name: 'Hugging Face',
    slug: 'huggingface',
    shortDesc: 'AI 模型和数据集开源平台',
    description: 'Hugging Face 是 AI 领域最大的开源社区，提供预训练模型、数据集和工具，支持自然语言处理、计算机视觉等多种任务。',
    websiteUrl: 'https://huggingface.co',
    githubUrl: 'https://github.com/huggingface',
    logoUrl: '',
    pricingType: 'FREEMIUM',
    tags: '开源,模型库,数据集,NLP',
    stars: 150000,
    upvotes: 45000,
    source: 'manual',
    isFeatured: true,
  },
  {
    name: 'LangChain',
    slug: 'langchain',
    shortDesc: '构建 LLM 应用的框架',
    description: 'LangChain 是一个用于开发由语言模型驱动的应用程序的框架，支持链式调用、记忆、工具使用等高级功能。',
    websiteUrl: 'https://langchain.com',
    githubUrl: 'https://github.com/langchain-ai/langchain',
    logoUrl: '',
    pricingType: 'OPEN_SOURCE',
    tags: '开源,框架,LLM,开发工具',
    stars: 95000,
    upvotes: 28000,
    source: 'manual',
    isFeatured: false,
  },
  {
    name: 'AutoGPT',
    slug: 'autogpt',
    shortDesc: '自主运行的 AI 代理',
    description: 'AutoGPT 是一个实验性的开源项目，展示了 GPT-4 自主完成任务的能力，可以自动分解目标并执行多步骤操作。',
    websiteUrl: 'https://agpt.co',
    githubUrl: 'https://github.com/Significant-Gravitas/AutoGPT',
    logoUrl: '',
    pricingType: 'OPEN_SOURCE',
    tags: '开源,AI代理,自动化,GPT-4',
    stars: 165000,
    upvotes: 35000,
    source: 'manual',
    isFeatured: false,
  },
]

async function main() {
  console.log('🌱 开始填充种子数据...')
  
  for (const tool of realTools) {
    await prisma.tool.upsert({
      where: { slug: tool.slug },
      update: {
        ...tool,
        updatedAt: new Date(),
      },
      create: {
        ...tool,
        isActive: true,
        publishedAt: new Date(),
      },
    })
    console.log(`✅ ${tool.name}`)
  }
  
  const count = await prisma.tool.count()
  console.log(`\n📊 数据库中共有 ${count} 个工具`)
  console.log('✨ 种子数据填充完成！')
  
  await prisma.$disconnect()
}

main().catch(async (e) => {
  console.error(e)
  await prisma.$disconnect()
  process.exit(1)
})
