/**
 * AI 工具爬虫脚本
 * 从多个数据源爬取 AI 工具信息并导入数据库
 */

import { PrismaClient } from '@prisma/client';

// slugify 函数 - 支持中文
function slugify(text: string): string {
  // 如果是中文，使用拼音或保留中文
  const hasChinese = /[\u4e00-\u9fa5]/.test(text);
  if (hasChinese) {
    // 中文工具使用英文名+随机数，或保留中文转义
    const base = text
      .replace(/[^\w\u4e00-\u9fa5\s-]/g, '')
      .replace(/\s+/g, '-')
      .substring(0, 30);
    return `${base}-${Math.random().toString(36).substring(2, 6)}`;
  }
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .substring(0, 50);
}

const prisma = new PrismaClient();

// 分类映射
const categoryMap: Record<string, string> = {
  'chat': '聊天对话',
  'writing': '写作助手',
  'image': '图像生成',
  'video': '视频生成',
  'audio': '音频处理',
  'code': '代码助手',
  'search': '搜索引擎',
  'productivity': '办公效率',
  'design': '设计工具',
  'knowledge': '知识管理',
  'translation': '翻译工具',
  'data': '数据分析',
  'education': '教育学习',
  'health': '健康医疗',
  'finance': '金融理财',
  'other': '其他工具',
};

// 模拟的 AI 工具数据（实际项目中应该从真实 API 或网页爬取）
const mockTools = [
  // 聊天对话类
  { name: 'ChatGPT', description: 'OpenAI 开发的对话式 AI 助手，支持多种任务', category: 'chat', url: 'https://chat.openai.com', pricing: 'free_paid', tags: ['OpenAI', 'GPT', '对话'] },
  { name: 'Claude', description: 'Anthropic 开发的 AI 助手，擅长长文本处理', category: 'chat', url: 'https://claude.ai', pricing: 'free_paid', tags: ['Anthropic', '长文本', '对话'] },
  { name: 'Gemini', description: 'Google 开发的多模态 AI 模型', category: 'chat', url: 'https://gemini.google.com', pricing: 'free_paid', tags: ['Google', '多模态', '对话'] },
  { name: '文心一言', description: '百度开发的对话式 AI 产品', category: 'chat', url: 'https://yiyan.baidu.com', pricing: 'free', tags: ['百度', '中文', '对话'] },
  { name: '通义千问', description: '阿里云开发的大语言模型', category: 'chat', url: 'https://tongyi.aliyun.com', pricing: 'free_paid', tags: ['阿里', '中文', '对话'] },
  { name: 'Kimi', description: '月之暗面开发的长文本 AI 助手', category: 'chat', url: 'https://kimi.moonshot.cn', pricing: 'free_paid', tags: ['月之暗面', '长文本', '中文'] },
  { name: '智谱清言', description: '智谱 AI 开发的对话助手', category: 'chat', url: 'https://chatglm.cn', pricing: 'free', tags: ['智谱', 'ChatGLM', '中文'] },
  { name: '讯飞星火', description: '科大讯飞开发的认知大模型', category: 'chat', url: 'https://xinghuo.xfyun.cn', pricing: 'free', tags: ['讯飞', '中文', '语音'] },
  { name: '豆包', description: '字节跳动开发的 AI 助手', category: 'chat', url: 'https://www.doubao.com', pricing: 'free', tags: ['字节', '中文', '多模态'] },
  { name: 'Perplexity', description: 'AI 驱动的搜索引擎，提供带引用的答案', category: 'search', url: 'https://www.perplexity.ai', pricing: 'free_paid', tags: ['搜索', '引用', '研究'] },
  
  // 图像生成类
  { name: 'Midjourney', description: '顶级 AI 图像生成工具，艺术风格出色', category: 'image', url: 'https://www.midjourney.com', pricing: 'paid', tags: ['图像生成', '艺术', 'Discord'] },
  { name: 'DALL-E 3', description: 'OpenAI 的图像生成模型', category: 'image', url: 'https://openai.com/dall-e-3', pricing: 'paid', tags: ['OpenAI', '图像生成', '多模态'] },
  { name: 'Stable Diffusion', description: '开源图像生成模型，可本地部署', category: 'image', url: 'https://stability.ai', pricing: 'free', tags: ['开源', '图像生成', '本地'] },
  { name: 'Leonardo.ai', description: '游戏资产和创意图像生成平台', category: 'image', url: 'https://leonardo.ai', pricing: 'free_paid', tags: ['图像生成', '游戏', '3D'] },
  { name: 'Adobe Firefly', description: 'Adobe 的创意生成式 AI 工具', category: 'image', url: 'https://www.adobe.com/sensei/generative-ai/firefly.html', pricing: 'free_paid', tags: ['Adobe', '图像生成', '设计'] },
  { name: 'Playground', description: '免费的 AI 图像生成和编辑平台', category: 'image', url: 'https://playgroundai.com', pricing: 'free_paid', tags: ['图像生成', '编辑', '免费'] },
  { name: 'Ideogram', description: '擅长文字渲染的 AI 图像生成器', category: 'image', url: 'https://ideogram.ai', pricing: 'free_paid', tags: ['图像生成', '文字', '设计'] },
  { name: 'Recraft', description: '专业矢量图形 AI 生成工具', category: 'image', url: 'https://www.recraft.ai', pricing: 'free_paid', tags: ['矢量', '设计', 'SVG'] },
  { name: '文心一格', description: '百度的 AI 艺术和创意辅助平台', category: 'image', url: 'https://yige.baidu.com', pricing: 'free', tags: ['百度', '中文', '艺术'] },
  { name: '通义万相', description: '阿里云的 AI 绘画创作模型', category: 'image', url: 'https://tongyi.aliyun.com/wanxiang', pricing: 'free', tags: ['阿里', '中文', '绘画'] },
  
  // 视频生成类
  { name: 'Runway', description: 'AI 视频生成和编辑平台', category: 'video', url: 'https://runwayml.com', pricing: 'free_paid', tags: ['视频生成', '编辑', 'Gen-2'] },
  { name: 'Pika', description: 'AI 视频生成工具，文本/图像转视频', category: 'video', url: 'https://pika.art', pricing: 'free_paid', tags: ['视频生成', '文本转视频', '图像转视频'] },
  { name: 'HeyGen', description: 'AI 数字人视频生成平台', category: 'video', url: 'https://www.heygen.com', pricing: 'paid', tags: ['数字人', '视频', '翻译'] },
  { name: 'Sora', description: 'OpenAI 的文本生成视频模型', category: 'video', url: 'https://openai.com/sora', pricing: 'paid', tags: ['OpenAI', '视频生成', '文本转视频'] },
  { name: 'Kling', description: '快手的 AI 视频生成模型', category: 'video', url: 'https://klingai.com', pricing: 'free_paid', tags: ['快手', '视频生成', '中文'] },
  { name: 'Luma Dream Machine', description: 'Luma 的 AI 视频生成工具', category: 'video', url: 'https://lumalabs.ai/dream-machine', pricing: 'free_paid', tags: ['视频生成', '3D', 'Luma'] },
  { name: 'Haiper', description: '免费的 AI 视频生成平台', category: 'video', url: 'https://haiper.ai', pricing: 'free', tags: ['视频生成', '免费', '文本转视频'] },
  { name: 'PixVerse', description: 'AI 视频生成和编辑工具', category: 'video', url: 'https://pixverse.ai', pricing: 'free_paid', tags: ['视频生成', '动漫', '免费'] },
  { name: 'Morph Studio', description: 'AI 视频创作平台', category: 'video', url: 'https://www.morphstudio.com', pricing: 'free_paid', tags: ['视频生成', '社区', '创作'] },
  { name: 'Stable Video', description: 'Stability AI 的视频生成工具', category: 'video', url: 'https://www.stablevideo.com', pricing: 'free_paid', tags: ['Stability', '视频生成', '图像转视频'] },
  
  // 代码助手类
  { name: 'GitHub Copilot', description: 'GitHub 的 AI 编程助手', category: 'code', url: 'https://github.com/features/copilot', pricing: 'paid', tags: ['GitHub', '编程', '代码补全'] },
  { name: 'Cursor', description: 'AI 驱动的代码编辑器', category: 'code', url: 'https://cursor.sh', pricing: 'free_paid', tags: ['编辑器', '编程', 'VS Code'] },
  { name: 'Codeium', description: '免费的 AI 代码补全工具', category: 'code', url: 'https://codeium.com', pricing: 'free', tags: ['编程', '代码补全', '免费'] },
  { name: 'Tabnine', description: 'AI 代码补全工具', category: 'code', url: 'https://www.tabnine.com', pricing: 'free_paid', tags: ['编程', '代码补全', '隐私'] },
  { name: 'Replit Ghostwriter', description: 'Replit 的 AI 编程助手', category: 'code', url: 'https://replit.com/site/ghostwriter', pricing: 'paid', tags: ['Replit', '编程', '云端'] },
  { name: 'Amazon CodeWhisperer', description: 'AWS 的 AI 代码生成器', category: 'code', url: 'https://aws.amazon.com/codewhisperer', pricing: 'free_paid', tags: ['AWS', '编程', '云'] },
  { name: 'JetBrains AI', description: 'JetBrains IDE 的 AI 助手', category: 'code', url: 'https://www.jetbrains.com/ai', pricing: 'paid', tags: ['JetBrains', 'IDE', '编程'] },
  { name: 'Sourcegraph Cody', description: 'AI 代码搜索和助手', category: 'code', url: 'https://sourcegraph.com/cody', pricing: 'free_paid', tags: ['代码搜索', '编程', '企业'] },
  { name: 'Continue', description: '开源的 AI 代码助手插件', category: 'code', url: 'https://continue.dev', pricing: 'free', tags: ['开源', '编程', 'VS Code'] },
  { name: 'CodeGeeX', description: '智谱 AI 的代码生成模型', category: 'code', url: 'https://codegeex.cn', pricing: 'free', tags: ['智谱', '中文', '编程'] },
  
  // 写作助手类
  { name: 'Jasper', description: 'AI 写作助手，专注营销内容', category: 'writing', url: 'https://www.jasper.ai', pricing: 'paid', tags: ['写作', '营销', 'SEO'] },
  { name: 'Copy.ai', description: 'AI 文案写作工具', category: 'writing', url: 'https://www.copy.ai', pricing: 'free_paid', tags: ['写作', '文案', '营销'] },
  { name: 'Notion AI', description: 'Notion 内置的 AI 写作助手', category: 'writing', url: 'https://www.notion.so/product/ai', pricing: 'paid', tags: ['Notion', '写作', '笔记'] },
  { name: 'Grammarly', description: 'AI 写作辅助和语法检查', category: 'writing', url: 'https://www.grammarly.com', pricing: 'free_paid', tags: ['写作', '语法', '校对'] },
  { name: 'QuillBot', description: 'AI 改写和润色工具', category: 'writing', url: 'https://quillbot.com', pricing: 'free_paid', tags: ['改写', '润色', '写作'] },
  { name: 'Writesonic', description: 'AI 内容创作平台', category: 'writing', url: 'https://writesonic.com', pricing: 'free_paid', tags: ['写作', '营销', 'SEO'] },
  { name: 'Rytr', description: 'AI 写作助手', category: 'writing', url: 'https://rytr.me', pricing: 'free_paid', tags: ['写作', '文案', '博客'] },
  { name: '秘塔写作猫', description: '中文 AI 写作辅助工具', category: 'writing', url: 'https://xiezuocat.com', pricing: 'free_paid', tags: ['中文', '写作', '校对'] },
  { name: '火山写作', description: '字节跳动的 AI 写作助手', category: 'writing', url: 'https://www.writingo.net', pricing: 'free', tags: ['字节', '中文', '写作'] },
  { name: '讯飞听见', description: '讯飞语音转文字和写作工具', category: 'writing', url: 'https://www.iflyrec.com', pricing: 'free_paid', tags: ['讯飞', '语音', '转写'] },
  
  // 音频处理类
  { name: 'ElevenLabs', description: '顶级 AI 语音合成平台', category: 'audio', url: 'https://elevenlabs.io', pricing: 'free_paid', tags: ['语音合成', 'TTS', '配音'] },
  { name: 'Murf', description: 'AI 语音生成器', category: 'audio', url: 'https://murf.ai', pricing: 'free_paid', tags: ['语音合成', '配音', '视频'] },
  { name: 'Descript', description: 'AI 音频和视频编辑工具', category: 'audio', url: 'https://www.descript.com', pricing: 'free_paid', tags: ['音频编辑', '视频', '播客'] },
  { name: 'Whisper', description: 'OpenAI 的开源语音识别模型', category: 'audio', url: 'https://openai.com/research/whisper', pricing: 'free', tags: ['OpenAI', '语音识别', '开源'] },
  { name: 'Suno', description: 'AI 音乐生成工具', category: 'audio', url: 'https://www.suno.ai', pricing: 'free_paid', tags: ['音乐生成', 'AI音乐', '创作'] },
  { name: 'Udio', description: 'AI 音乐创作平台', category: 'audio', url: 'https://www.udio.com', pricing: 'free_paid', tags: ['音乐生成', 'AI音乐', '创作'] },
  { name: 'AIVA', description: 'AI 音乐作曲助手', category: 'audio', url: 'https://www.aiva.ai', pricing: 'free_paid', tags: ['音乐', '作曲', '配乐'] },
  { name: 'Soundraw', description: 'AI 免版税音乐生成', category: 'audio', url: 'https://soundraw.io', pricing: 'paid', tags: ['音乐', '免版税', '视频配乐'] },
  { name: 'LALAL.AI', description: 'AI 音频分离工具', category: 'audio', url: 'https://www.lalal.ai', pricing: 'free_paid', tags: ['音频分离', '人声', '伴奏'] },
  { name: 'Adobe Podcast', description: 'Adobe 的 AI 音频增强工具', category: 'audio', url: 'https://podcast.adobe.com', pricing: 'free', tags: ['Adobe', '音频增强', '播客'] },
  
  // 设计工具类
  { name: 'Canva AI', description: 'Canva 的 AI 设计功能', category: 'design', url: 'https://www.canva.com', pricing: 'free_paid', tags: ['设计', '图形', '模板'] },
  { name: 'Figma AI', description: 'Figma 的 AI 设计助手', category: 'design', url: 'https://www.figma.com/ai', pricing: 'free_paid', tags: ['设计', 'UI', '协作'] },
  { name: 'Looka', description: 'AI Logo 生成器', category: 'design', url: 'https://looka.com', pricing: 'paid', tags: ['Logo', '品牌', '设计'] },
  { name: 'Remove.bg', description: 'AI 自动抠图工具', category: 'design', url: 'https://www.remove.bg', pricing: 'free_paid', tags: ['抠图', '背景移除', '图像'] },
  { name: 'Uizard', description: 'AI UI/UX 设计工具', category: 'design', url: 'https://uizard.io', pricing: 'free_paid', tags: ['UI设计', '原型', '线框图'] },
  { name: 'Galileo AI', description: 'AI UI 设计生成器', category: 'design', url: 'https://www.usegalileo.ai', pricing: 'paid', tags: ['UI设计', 'Figma', '生成'] },
  { name: 'Khroma', description: 'AI 配色方案生成器', category: 'design', url: 'https://khroma.co', pricing: 'free', tags: ['配色', '设计', '色彩'] },
  { name: 'Fontjoy', description: 'AI 字体配对工具', category: 'design', url: 'https://fontjoy.com', pricing: 'free', tags: ['字体', '排版', '设计'] },
  { name: 'Visily', description: 'AI 线框图转高保真设计', category: 'design', url: 'https://www.visily.ai', pricing: 'free', tags: ['线框图', 'UI设计', '原型'] },
  { name: 'Autodraw', description: 'Google 的 AI 绘图工具', category: 'design', url: 'https://www.autodraw.com', pricing: 'free', tags: ['Google', '绘图', '草图'] },
  
  // 办公效率类
  { name: 'Microsoft Copilot', description: 'Microsoft 365 的 AI 助手', category: 'productivity', url: 'https://copilot.microsoft.com', pricing: 'paid', tags: ['微软', '办公', '生产力'] },
  { name: 'Gamma', description: 'AI 演示文稿生成器', category: 'productivity', url: 'https://gamma.app', pricing: 'free_paid', tags: ['PPT', '演示', '文档'] },
  { name: 'Tome', description: 'AI 故事和演示生成器', category: 'productivity', url: 'https://tome.app', pricing: 'free_paid', tags: ['PPT', '演示', '故事'] },
  { name: 'Beautiful.ai', description: 'AI 演示文稿设计工具', category: 'productivity', url: 'https://www.beautiful.ai', pricing: 'paid', tags: ['PPT', '设计', '演示'] },
  { name: 'Otter.ai', description: 'AI 会议记录和转录', category: 'productivity', url: 'https://otter.ai', pricing: 'free_paid', tags: ['会议', '转录', '笔记'] },
  { name: 'Fireflies', description: 'AI 会议助手', category: 'productivity', url: 'https://fireflies.ai', pricing: 'free_paid', tags: ['会议', '转录', '搜索'] },
  { name: 'Mem', description: 'AI 驱动的笔记应用', category: 'productivity', url: 'https://mem.ai', pricing: 'free_paid', tags: ['笔记', '知识', '搜索'] },
  { name: 'Taskade', description: 'AI 任务和项目管理', category: 'productivity', url: 'https://www.taskade.com', pricing: 'free_paid', tags: ['任务', '协作', '笔记'] },
  { name: 'Clockwise', description: 'AI 日程优化工具', category: 'productivity', url: 'https://www.getclockwise.com', pricing: 'free_paid', tags: ['日程', '日历', '效率'] },
  { name: 'Reclaim', description: 'AI 日程管理助手', category: 'productivity', url: 'https://reclaim.ai', pricing: 'free_paid', tags: ['日程', '日历', '习惯'] },
  
  // 知识管理类
  { name: 'Obsidian', description: '强大的本地知识库工具', category: 'knowledge', url: 'https://obsidian.md', pricing: 'free_paid', tags: ['笔记', '知识库', '本地'] },
  { name: 'Notion', description: '全能工作空间和笔记工具', category: 'knowledge', url: 'https://www.notion.so', pricing: 'free_paid', tags: ['笔记', '数据库', '协作'] },
  { name: 'Roam Research', description: '双向链接笔记工具', category: 'knowledge', url: 'https://roamresearch.com', pricing: 'paid', tags: ['笔记', '双向链接', '思维'] },
  { name: 'Logseq', description: '开源的双向链接笔记', category: 'knowledge', url: 'https://logseq.com', pricing: 'free', tags: ['开源', '笔记', '本地'] },
  { name: 'Readwise', description: '阅读高亮和笔记管理', category: 'knowledge', url: 'https://readwise.io', pricing: 'paid', tags: ['阅读', '笔记', '高亮'] },
  { name: 'Zotero', description: '文献管理和引用工具', category: 'knowledge', url: 'https://www.zotero.org', pricing: 'free', tags: ['文献', '学术', '引用'] },
  { name: 'Wolfram Alpha', description: '计算知识和问答引擎', category: 'knowledge', url: 'https://www.wolframalpha.com', pricing: 'free_paid', tags: ['计算', '知识', '数学'] },
  { name: 'Elicit', description: 'AI 研究助手', category: 'knowledge', url: 'https://elicit.org', pricing: 'free_paid', tags: ['研究', '学术', '论文'] },
  { name: 'Consensus', description: 'AI 科学论文搜索', category: 'knowledge', url: 'https://consensus.app', pricing: 'free_paid', tags: ['学术', '论文', '研究'] },
  { name: 'Semantic Scholar', description: 'AI 驱动的学术搜索引擎', category: 'knowledge', url: 'https://www.semanticscholar.org', pricing: 'free', tags: ['学术', '论文', 'AI'] },
  
  // 翻译工具类
  { name: 'DeepL', description: '高质量 AI 翻译工具', category: 'translation', url: 'https://www.deepl.com', pricing: 'free_paid', tags: ['翻译', '高质量', '文档'] },
  { name: 'Google Translate', description: 'Google 的翻译服务', category: 'translation', url: 'https://translate.google.com', pricing: 'free', tags: ['Google', '翻译', '多语言'] },
  { name: '沉浸式翻译', description: '双语对照网页翻译插件', category: 'translation', url: 'https://immersivetranslate.com', pricing: 'free_paid', tags: ['翻译', '浏览器', '双语'] },
  { name: '彩云小译', description: '中文 AI 翻译工具', category: 'translation', url: 'https://fanyi.caiyunapp.com', pricing: 'free_paid', tags: ['中文', '翻译', '文档'] },
  { name: '有道翻译', description: '网易的翻译服务', category: 'translation', url: 'https://fanyi.youdao.com', pricing: 'free_paid', tags: ['网易', '翻译', '中文'] },
  { name: 'Smartcat', description: 'AI 翻译管理平台', category: 'translation', url: 'https://www.smartcat.com', pricing: 'free_paid', tags: ['翻译', '协作', '专业'] },
  { name: 'MateCat', description: '开源计算机辅助翻译', category: 'translation', url: 'https://www.matecat.com', pricing: 'free', tags: ['开源', '翻译', 'CAT'] },
  { name: 'Papago', description: 'Naver 的翻译服务', category: 'translation', url: 'https://papago.naver.com', pricing: 'free', tags: ['Naver', '韩语', '亚洲语言'] },
  { name: 'QuillBot', description: 'AI 改写和翻译工具', category: 'translation', url: 'https://quillbot.com', pricing: 'free_paid', tags: ['改写', '翻译', '写作'] },
  { name: 'Reverso', description: '语境翻译和学习工具', category: 'translation', url: 'https://www.reverso.net', pricing: 'free_paid', tags: ['翻译', '语境', '学习'] },
  
  // 数据分析类
  { name: 'ChatExcel', description: '聊天式 Excel 处理工具', category: 'data', url: 'https://chatexcel.com', pricing: 'free_paid', tags: ['Excel', '表格', '中文'] },
  { name: 'Julius AI', description: 'AI 数据分析和可视化', category: 'data', url: 'https://julius.ai', pricing: 'free_paid', tags: ['数据分析', '可视化', '图表'] },
  { name: 'Ajelix', description: 'AI Excel 和 Google Sheets 助手', category: 'data', url: 'https://ajelix.com', pricing: 'free_paid', tags: ['Excel', '表格', '公式'] },
  { name: 'Rows', description: 'AI 电子表格工具', category: 'data', url: 'https://rows.com', pricing: 'free_paid', tags: ['表格', '数据', '协作'] },
  { name: 'Tableau AI', description: 'Tableau 的 AI 分析功能', category: 'data', url: 'https://www.tableau.com', pricing: 'paid', tags: ['数据可视化', 'BI', '企业'] },
  { name: 'Power BI', description: '微软的商业智能工具', category: 'data', url: 'https://powerbi.microsoft.com', pricing: 'paid', tags: ['微软', 'BI', '数据'] },
  { name: 'Hex', description: 'AI 数据科学笔记本', category: 'data', url: 'https://hex.tech', pricing: 'free_paid', tags: ['数据科学', 'Python', 'SQL'] },
  { name: 'Seek AI', description: '自然语言数据分析', category: 'data', url: 'https://www.seek.ai', pricing: 'paid', tags: ['SQL', '数据', '自然语言'] },
  { name: 'Obviously AI', description: '无代码 AI 数据分析', category: 'data', url: 'https://www.obviously.ai', pricing: 'paid', tags: ['无代码', '预测', 'ML'] },
  { name: 'Akkio', description: '无代码 AI 数据分析平台', category: 'data', url: 'https://www.akkio.com', pricing: 'paid', tags: ['无代码', 'ML', '预测'] },
  
  // 教育学习类
  { name: 'Khan Academy', description: '可汗学院的 AI 导师 Khanmigo', category: 'education', url: 'https://www.khanacademy.org', pricing: 'free', tags: ['教育', '学习', '辅导'] },
  { name: 'Duolingo', description: 'AI 语言学习应用', category: 'education', url: 'https://www.duolingo.com', pricing: 'free_paid', tags: ['语言', '学习', '游戏化'] },
  { name: 'Quizlet', description: 'AI 学习卡片和测试', category: 'education', url: 'https://quizlet.com', pricing: 'free_paid', tags: ['学习', '卡片', '记忆'] },
  { name: 'Coursera', description: '在线课程平台', category: 'education', url: 'https://www.coursera.org', pricing: 'free_paid', tags: ['课程', '证书', '大学'] },
  { name: 'Udemy', description: '在线技能学习平台', category: 'education', url: 'https://www.udemy.com', pricing: 'paid', tags: ['课程', '技能', '视频'] },
  { name: 'Brilliant', description: '互动式 STEM 学习', category: 'education', url: 'https://brilliant.org', pricing: 'paid', tags: ['数学', '科学', '编程'] },
  { name: 'Photomath', description: 'AI 数学解题应用', category: 'education', url: 'https://photomath.com', pricing: 'free_paid', tags: ['数学', '解题', '扫描'] },
  { name: 'Socratic', description: 'Google 的 AI 学习助手', category: 'education', url: 'https://socratic.org', pricing: 'free', tags: ['Google', '学习', '作业'] },
  { name: 'Chegg', description: '学习辅导和作业帮助', category: 'education', url: 'https://www.chegg.com', pricing: 'paid', tags: ['辅导', '作业', '教科书'] },
  { name: 'Course Hero', description: '学习资源和辅导', category: 'education', url: 'https://www.coursehero.com', pricing: 'paid', tags: ['学习', '笔记', '辅导'] },
  
  // 健康医疗类
  { name: 'Ada', description: 'AI 症状检查器', category: 'health', url: 'https://ada.com', pricing: 'free', tags: ['健康', '症状', '诊断'] },
  { name: 'Babylon', description: 'AI 健康助手', category: 'health', url: 'https://www.babylonhealth.com', pricing: 'free_paid', tags: ['健康', '医疗', '咨询'] },
  { name: 'Woebot', description: 'AI 心理健康助手', category: 'health', url: 'https://woebothealth.com', pricing: 'free', tags: ['心理健康', 'CBT', '聊天'] },
  { name: 'Wysa', description: 'AI 心理健康应用', category: 'health', url: 'https://www.wysa.io', pricing: 'free_paid', tags: ['心理健康', '情绪', '支持'] },
  { name: 'Youper', description: 'AI 情绪健康助手', category: 'health', url: 'https://www.youper.ai', pricing: 'free_paid', tags: ['情绪', '心理健康', 'CBT'] },
  { name: 'SkinVision', description: 'AI 皮肤癌检测', category: 'health', url: 'https://www.skinvision.com', pricing: 'paid', tags: ['皮肤', '健康', '检测'] },
  { name: 'Aaptiv', description: 'AI 健身指导', category: 'health', url: 'https://aaptiv.com', pricing: 'paid', tags: ['健身', '运动', '教练'] },
  { name: 'Freeletics', description: 'AI 个性化健身', category: 'health', url: 'https://www.freeletics.com', pricing: 'free_paid', tags: ['健身', '训练', '个性化'] },
  { name: 'Noom', description: 'AI 减肥和健康教练', category: 'health', url: 'https://www.noom.com', pricing: 'paid', tags: ['减肥', '健康', '营养'] },
  { name: 'Headspace', description: '冥想和心理健康', category: 'health', url: 'https://www.headspace.com', pricing: 'free_paid', tags: ['冥想', '正念', '睡眠'] },
  
  // 金融理财类
  { name: 'Cleo', description: 'AI 财务助手', category: 'finance', url: 'https://www.meetcleo.com', pricing: 'free_paid', tags: ['财务', '预算', '储蓄'] },
  { name: 'YNAB', description: '预算管理应用', category: 'finance', url: 'https://www.youneedabudget.com', pricing: 'paid', tags: ['预算', '理财', '规划'] },
  { name: 'PocketGuard', description: 'AI 预算助手', category: 'finance', url: 'https://pocketguard.com', pricing: 'free_paid', tags: ['预算', '支出', '节省'] },
  { name: 'Albert', description: 'AI 理财顾问', category: 'finance', url: 'https://albert.com', pricing: 'free_paid', tags: ['理财', '投资', '储蓄'] },
  { name: 'Mint', description: '个人财务管理', category: 'finance', url: 'https://mint.intuit.com', pricing: 'free', tags: ['财务', '预算', '追踪'] },
  { name: 'Personal Capital', description: '财富管理和投资追踪', category: 'finance', url: 'https://www.personalcapital.com', pricing: 'free', tags: ['投资', '财富', '退休'] },
  { name: 'Betterment', description: 'AI 投资顾问', category: 'finance', url: 'https://www.betterment.com', pricing: 'paid', tags: ['投资', '顾问', '自动化'] },
  { name: 'Wealthfront', description: '自动化投资平台', category: 'finance', url: 'https://www.wealthfront.com', pricing: 'paid', tags: ['投资', '自动化', '理财'] },
  { name: 'Kavout', description: 'AI 股票分析', category: 'finance', url: 'https://www.kavout.com', pricing: 'paid', tags: ['股票', '分析', '投资'] },
  { name: 'Tiller', description: 'AI 财务电子表格', category: 'finance', url: 'https://www.tillerhq.com', pricing: 'paid', tags: ['财务', '表格', '自动化'] },
  
  // 其他工具类
  { name: 'IFTTT', description: '自动化工作流平台', category: 'other', url: 'https://ifttt.com', pricing: 'free_paid', tags: ['自动化', '工作流', '集成'] },
  { name: 'Zapier', description: '应用自动化连接', category: 'other', url: 'https://zapier.com', pricing: 'free_paid', tags: ['自动化', '集成', '工作流'] },
  { name: 'Make', description: '可视化自动化平台', category: 'other', url: 'https://www.make.com', pricing: 'free_paid', tags: ['自动化', '可视化', '集成'] },
  { name: 'n8n', description: '开源工作流自动化', category: 'other', url: 'https://n8n.io', pricing: 'free_paid', tags: ['开源', '自动化', '工作流'] },
  { name: 'Hugging Face', description: 'AI 模型和数据集平台', category: 'other', url: 'https://huggingface.co', pricing: 'free_paid', tags: ['开源', '模型', '社区'] },
  { name: 'Replicate', description: 'AI 模型运行平台', category: 'other', url: 'https://replicate.com', pricing: 'paid', tags: ['模型', 'API', '部署'] },
  { name: 'LangChain', description: 'LLM 应用开发框架', category: 'other', url: 'https://www.langchain.com', pricing: 'free', tags: ['开源', 'LLM', '开发'] },
  { name: 'Flowise', description: '可视化 LangChain 构建器', category: 'other', url: 'https://flowiseai.com', pricing: 'free', tags: ['开源', 'LangChain', '可视化'] },
  { name: 'Vercel', description: '前端部署和 AI 应用平台', category: 'other', url: 'https://vercel.com', pricing: 'free_paid', tags: ['部署', '前端', 'AI'] },
  { name: 'Railway', description: '应用部署平台', category: 'other', url: 'https://railway.app', pricing: 'free_paid', tags: ['部署', '后端', '全栈'] },
  
  // 聊天对话类 - 扩展
  { name: 'Poe', description: 'Quora 推出的 AI 聊天聚合平台', category: 'chat', url: 'https://poe.com', pricing: 'free_paid', tags: ['聚合', '多模型', '聊天'] },
  { name: 'Character.AI', description: '创建和与 AI 角色对话', category: 'chat', url: 'https://character.ai', pricing: 'free_paid', tags: ['角色', '娱乐', '对话'] },
  { name: 'Grok', description: 'xAI 开发的对话模型', category: 'chat', url: 'https://grok.x.ai', pricing: 'paid', tags: ['xAI', '马斯克', '实时'] },
  { name: 'YouChat', description: 'You.com 的 AI 聊天助手', category: 'chat', url: 'https://you.com', pricing: 'free_paid', tags: ['搜索', '聊天', '引用'] },
  { name: 'Pi', description: 'Inflection AI 的个人助手', category: 'chat', url: 'https://pi.ai', pricing: 'free', tags: ['个人助手', '友好', '情感'] },
  { name: 'Mistral Chat', description: 'Mistral AI 的对话助手', category: 'chat', url: 'https://chat.mistral.ai', pricing: 'free_paid', tags: ['Mistral', '欧洲', '开源'] },
  { name: 'Cohere Chat', description: 'Cohere 的企业级对话 AI', category: 'chat', url: 'https://cohere.com', pricing: 'free_paid', tags: ['企业', 'API', '嵌入'] },
  { name: 'DeepSeek', description: '深度求索的大语言模型', category: 'chat', url: 'https://chat.deepseek.com', pricing: 'free', tags: ['深度求索', '中文', '代码'] },
  { name: '百川智能', description: '王小川创立的 AI 公司', category: 'chat', url: 'https://www.baichuan-ai.com', pricing: 'free', tags: ['百川', '中文', '搜索'] },
  { name: '零一万物', description: '李开复创办的 AI 公司', category: 'chat', url: 'https://www.01.ai', pricing: 'free', tags: ['零一万物', 'Yi', '中文'] },
  { name: '阶跃星辰', description: '国内大模型创业公司', category: 'chat', url: 'https://www.stepfun.com', pricing: 'free', tags: ['阶跃', '中文', '多模态'] },
  { name: 'MiniMax', description: '国内 AI 大模型公司', category: 'chat', url: 'https://www.minimaxi.com', pricing: 'free', tags: ['MiniMax', '中文', '语音'] },
  { name: '商汤商量', description: '商汤科技的大语言模型', category: 'chat', url: 'https://chat.sensetime.com', pricing: 'free', tags: ['商汤', '中文', '多模态'] },
  { name: '腾讯混元', description: '腾讯的大语言模型', category: 'chat', url: 'https://hunyuan.tencent.com', pricing: 'free', tags: ['腾讯', '中文', '多模态'] },
  { name: '华为盘古', description: '华为云的大模型', category: 'chat', url: 'https://pangu.huaweicloud.com', pricing: 'paid', tags: ['华为', '中文', '企业'] },
  { name: '天工 AI', description: '昆仑万维的 AI 助手', category: 'chat', url: 'https://www.tiangong.cn', pricing: 'free', tags: ['天工', '中文', '搜索'] },
  { name: '360智脑', description: '360 的大语言模型', category: 'chat', url: 'https://ai.360.com', pricing: 'free', tags: ['360', '中文', '安全'] },
  { name: '紫东太初', description: '中科院自动化所的多模态模型', category: 'chat', url: 'https://taichu.ia.ac.cn', pricing: 'free', tags: ['中科院', '多模态', '中文'] },
  { name: 'Wenxin', description: '百度文心大模型', category: 'chat', url: 'https://wenxin.baidu.com', pricing: 'free_paid', tags: ['百度', '中文', '大模型'] },
  { name: 'Aquila', description: '智源研究院的天鹰大模型', category: 'chat', url: 'https://www.01.ai', pricing: 'free', tags: ['智源', '开源', '中文'] },
  { name: 'ChatGLM3', description: '智谱 AI 第三代对话模型', category: 'chat', url: 'https://chatglm.cn', pricing: 'free', tags: ['智谱', '开源', '中文'] },
  
  // 图像生成类 - 扩展
  { name: 'Imagen 3', description: 'Google 最新图像生成模型', category: 'image', url: 'https://deepmind.google/technologies/imagen-3', pricing: 'paid', tags: ['Google', '高质量', '写实'] },
  { name: 'Flux', description: 'Black Forest Labs 的图像模型', category: 'image', url: 'https://flux1.ai', pricing: 'free_paid', tags: ['Flux', '开源', '高质量'] },
  { name: 'ComfyUI', description: 'Stable Diffusion 可视化工作流', category: 'image', url: 'https://comfyanonymous.github.io/ComfyUI', pricing: 'free', tags: ['开源', '工作流', '本地'] },
  { name: 'InvokeAI', description: 'Stable Diffusion 创作平台', category: 'image', url: 'https://invoke.ai', pricing: 'free', tags: ['开源', '创作', '本地'] },
  { name: 'Automatic1111', description: '最流行的 SD WebUI', category: 'image', url: 'https://github.com/AUTOMATIC1111', pricing: 'free', tags: ['开源', 'WebUI', '社区'] },
  { name: 'Fooocus', description: '简单易用的图像生成工具', category: 'image', url: 'https://fooocus.io', pricing: 'free', tags: ['开源', '简单', '本地'] },
  { name: 'Draw Things', description: 'iOS 本地图像生成应用', category: 'image', url: 'https://drawthings.app', pricing: 'free', tags: ['iOS', '本地', '移动端'] },
  { name: 'NightCafe', description: 'AI 艺术生成社区', category: 'image', url: 'https://nightcafe.studio', pricing: 'free_paid', tags: ['艺术', '社区', '创作'] },
  { name: 'Artbreeder', description: '协作式 AI 艺术创作', category: 'image', url: 'https://www.artbreeder.com', pricing: 'free_paid', tags: ['协作', '艺术', '混合'] },
  { name: 'DeepAI', description: 'AI 图像生成 API 平台', category: 'image', url: 'https://deepai.org', pricing: 'free_paid', tags: ['API', '图像生成', '文本转图像'] },
  { name: 'Craiyon', description: '免费的 AI 图像生成器', category: 'image', url: 'https://www.craiyon.com', pricing: 'free', tags: ['免费', '简单', '快速'] },
  { name: 'StarryAI', description: 'AI 艺术生成应用', category: 'image', url: 'https://starryai.com', pricing: 'free_paid', tags: ['艺术', '移动', '创作'] },
  { name: 'Wonder', description: '手机 AI 艺术应用', category: 'image', url: 'https://www.wonder.ai', pricing: 'free_paid', tags: ['移动', '艺术', '简单'] },
  { name: 'Dream by Wombo', description: '流行的 AI 艺术应用', category: 'image', url: 'https://www.wombo.art', pricing: 'free_paid', tags: ['移动', '艺术', '社区'] },
  { name: 'Canva AI', description: 'Canva 的 AI 设计功能', category: 'image', url: 'https://www.canva.com/ai-image-generator', pricing: 'free_paid', tags: ['Canva', '设计', '模板'] },
  { name: 'Remove.bg', description: 'AI 背景移除工具', category: 'image', url: 'https://www.remove.bg', pricing: 'free_paid', tags: ['背景移除', '图像编辑', 'API'] },
  { name: 'Upscayl', description: '开源 AI 图像放大工具', category: 'image', url: 'https://upscayl.org', pricing: 'free', tags: ['开源', '放大', '画质提升'] },
  { name: 'GFPGAN', description: '人脸修复和增强', category: 'image', url: 'https://github.com/TencentARC/GFPGAN', pricing: 'free', tags: ['开源', '人脸', '修复'] },
  { name: 'CodeFormer', description: '人脸复原和增强', category: 'image', url: 'https://github.com/sczhou/CodeFormer', pricing: 'free', tags: ['开源', '人脸', '复原'] },
  { name: 'ControlNet', description: '控制图像生成的条件模型', category: 'image', url: 'https://github.com/lllyasviel/ControlNet', pricing: 'free', tags: ['开源', '控制', '姿态'] },
  { name: 'Segment Anything', description: 'Meta 的图像分割模型', category: 'image', url: 'https://segment-anything.com', pricing: 'free', tags: ['Meta', '分割', '开源'] },
  { name: '妙鸭相机', description: '阿里推出的 AI 写真应用', category: 'image', url: 'https://www.miaoya.cn', pricing: 'paid', tags: ['阿里', '写真', '人像'] },
  { name: '美图秀秀 AI', description: '美图的 AI 图像功能', category: 'image', url: 'https://www.meitu.com', pricing: 'free_paid', tags: ['美图', '修图', '人像'] },
  { name: '稿定设计 AI', description: '稿定设计的 AI 功能', category: 'image', url: 'https://www.gaoding.com', pricing: 'free_paid', tags: ['稿定', '设计', '模板'] },
  { name: '创客贴 AI', description: '创客贴的 AI 设计功能', category: 'image', url: 'https://www.chuangkit.com', pricing: 'free_paid', tags: ['创客贴', '设计', '模板'] },
  { name: '即时 AI', description: '即时设计的 AI 功能', category: 'image', url: 'https://js.design/ai', pricing: 'free', tags: ['即时', '设计', 'UI'] },
  { name: 'MasterGo AI', description: 'MasterGo 的 AI 设计功能', category: 'image', url: 'https://mastergo.com', pricing: 'free', tags: ['MasterGo', '设计', 'UI'] },
  { name: 'Pixso AI', description: 'Pixso 的 AI 设计功能', category: 'image', url: 'https://pixso.cn', pricing: 'free', tags: ['Pixso', '设计', 'UI'] },
  
  // 视频生成类 - 扩展
  { name: 'D-ID', description: '照片开口说话的数字人', category: 'video', url: 'https://www.d-id.com', pricing: 'paid', tags: ['数字人', '照片说话', 'API'] },
  { name: 'Synthesia', description: '企业级 AI 视频生成', category: 'video', url: 'https://www.synthesia.io', pricing: 'paid', tags: ['企业', '数字人', '培训'] },
  { name: 'Pictory', description: '文本转视频工具', category: 'video', url: 'https://pictory.ai', pricing: 'paid', tags: ['文本转视频', '营销', '社交媒体'] },
  { name: 'InVideo', description: 'AI 视频创作平台', category: 'video', url: 'https://invideo.io', pricing: 'free_paid', tags: ['视频创作', '模板', '营销'] },
  { name: 'VEED.IO', description: '在线视频编辑和 AI 功能', category: 'video', url: 'https://www.veed.io', pricing: 'free_paid', tags: ['视频编辑', '字幕', '在线'] },
  { name: 'Descript', description: '音视频编辑和转录', category: 'video', url: 'https://www.descript.com', pricing: 'free_paid', tags: ['音视频', '转录', '编辑'] },
  { name: 'Fliki', description: '文本转视频和语音', category: 'video', url: 'https://fliki.ai', pricing: 'free_paid', tags: ['文本转视频', '语音', '内容'] },
  { name: 'Colossyan', description: 'AI 数字人视频平台', category: 'video', url: 'https://www.colossyan.com', pricing: 'paid', tags: ['数字人', '培训', '企业'] },
  { name: 'Elai.io', description: 'AI 数字人视频生成', category: 'video', url: 'https://elai.io', pricing: 'paid', tags: ['数字人', '视频', 'API'] },
  { name: 'Synthesys', description: 'AI 语音和视频生成', category: 'video', url: 'https://synthesys.io', pricing: 'paid', tags: ['语音', '视频', '数字人'] },
  { name: 'Rephrase.ai', description: '个性化视频生成', category: 'video', url: 'https://www.rephrase.ai', pricing: 'paid', tags: ['个性化', '视频', '营销'] },
  { name: 'Hour One', description: '虚拟人视频制作', category: 'video', url: 'https://hourone.ai', pricing: 'paid', tags: ['虚拟人', '视频', '企业'] },
  { name: 'DeepBrain AI', description: 'AI 主播和视频', category: 'video', url: 'https://www.deepbrain.io', pricing: 'paid', tags: ['AI主播', '视频', '新闻'] },
  { name: 'Runway Gen-3', description: 'Runway 最新视频生成模型', category: 'video', url: 'https://runwayml.com', pricing: 'paid', tags: ['视频生成', 'Gen-3', '高质量'] },
  { name: 'Luma Ray2', description: 'Luma 最新视频生成模型', category: 'video', url: 'https://lumalabs.ai', pricing: 'paid', tags: ['视频生成', 'Ray2', '高质量'] },
  { name: 'Pika 2.0', description: 'Pika 最新视频生成', category: 'video', url: 'https://pika.art', pricing: 'free_paid', tags: ['视频生成', 'Pika2', '场景'] },
  { name: '可灵 AI', description: '快手的 AI 视频生成', category: 'video', url: 'https://klingai.com', pricing: 'free_paid', tags: ['快手', '中文', '视频生成'] },
  { name: '即梦 AI', description: '剪映的 AI 视频生成', category: 'video', url: 'https://jimeng.jianying.com', pricing: 'free_paid', tags: ['剪映', '字节', '视频生成'] },
  { name: '海螺 AI', description: 'MiniMax 的视频生成', category: 'video', url: 'https://hailuoai.video', pricing: 'free', tags: ['MiniMax', '视频生成', '中文'] },
  { name: 'Vidu', description: '生数科技的视频生成', category: 'video', url: 'https://www.vidu.com', pricing: 'free_paid', tags: ['生数', '视频生成', '中文'] },
  { name: '清影', description: '智谱 AI 的视频生成', category: 'video', url: 'https://chatglm.cn/video', pricing: 'free', tags: ['智谱', '视频生成', '中文'] },
  { name: 'WHEE', description: '美图的视频生成', category: 'video', url: 'https://www.whee.com', pricing: 'free_paid', tags: ['美图', '视频生成', '中文'] },
  
  // 音频处理类 - 扩展
  { name: 'Suno', description: 'AI 音乐生成神器', category: 'audio', url: 'https://suno.ai', pricing: 'free_paid', tags: ['音乐生成', '歌曲', '创作'] },
  { name: 'Udio', description: 'AI 音乐生成平台', category: 'audio', url: 'https://www.udio.com', pricing: 'free_paid', tags: ['音乐生成', '歌曲', '高质量'] },
  { name: 'AIVA', description: 'AI 作曲助手', category: 'audio', url: 'https://www.aiva.ai', pricing: 'free_paid', tags: ['作曲', '古典', '配乐'] },
  { name: 'Soundraw', description: 'AI 生成免版税音乐', category: 'audio', url: 'https://soundraw.io', pricing: 'paid', tags: ['音乐', '免版税', '创作'] },
  { name: 'Boomy', description: 'AI 音乐创作平台', category: 'audio', url: 'https://boomy.com', pricing: 'free_paid', tags: ['音乐', '创作', '发行'] },
  { name: 'Amper Music', description: 'AI 音乐制作', category: 'audio', url: 'https://www.ampermusic.com', pricing: 'paid', tags: ['音乐', '制作', '企业'] },
  { name: 'Mubert', description: 'AI 生成免版税音乐', category: 'audio', url: 'https://mubert.com', pricing: 'free_paid', tags: ['音乐', '流媒体', 'API'] },
  { name: 'Endlesss', description: '协作音乐创作平台', category: 'audio', url: 'https://endlesss.fm', pricing: 'free_paid', tags: ['音乐', '协作', '创作'] },
  { name: 'Splash Pro', description: 'AI 节拍制作', category: 'audio', url: 'https://splashpro.com', pricing: 'free', tags: ['节拍', '音乐', '创作'] },
  { name: 'Loudly', description: 'AI 音乐生成', category: 'audio', url: 'https://www.loudly.com', pricing: 'free_paid', tags: ['音乐', '生成', '编辑'] },
  { name: 'Beatoven.ai', description: 'AI 免版税音乐', category: 'audio', url: 'https://www.beatoven.ai', pricing: 'free_paid', tags: ['音乐', '视频配乐', '免版税'] },
  { name: 'Epidemic Sound', description: '音乐库和音效', category: 'audio', url: 'https://www.epidemicsound.com', pricing: 'paid', tags: ['音乐库', '音效', '版权'] },
  { name: 'Artlist', description: '音乐授权平台', category: 'audio', url: 'https://artlist.io', pricing: 'paid', tags: ['音乐', '授权', '视频'] },
  { name: 'Musicbed', description: '高品质音乐授权', category: 'audio', url: 'https://www.musicbed.com', pricing: 'paid', tags: ['音乐', '授权', '高品质'] },
  { name: 'ElevenLabs', description: '顶级 AI 语音合成', category: 'audio', url: 'https://elevenlabs.io', pricing: 'free_paid', tags: ['语音合成', 'TTS', '克隆'] },
  { name: 'Play.ht', description: 'AI 语音生成', category: 'audio', url: 'https://play.ht', pricing: 'free_paid', tags: ['语音', 'TTS', '配音'] },
  { name: 'Speechify', description: '文本转语音阅读', category: 'audio', url: 'https://speechify.com', pricing: 'free_paid', tags: ['TTS', '阅读', '学习'] },
  { name: 'Murf.ai', description: 'AI 配音工作室', category: 'audio', url: 'https://murf.ai', pricing: 'free_paid', tags: ['配音', 'TTS', '视频'] },
  { name: 'Descript Overdub', description: '语音克隆和编辑', category: 'audio', url: 'https://www.descript.com/overdub', pricing: 'paid', tags: ['语音克隆', '编辑', 'TTS'] },
  { name: 'Resemble AI', description: 'AI 语音克隆', category: 'audio', url: 'https://www.resemble.ai', pricing: 'paid', tags: ['语音克隆', 'API', '游戏'] },
  { name: 'WellSaid', description: '企业级 AI 配音', category: 'audio', url: 'https://wellsaidlabs.com', pricing: 'paid', tags: ['配音', '企业', 'TTS'] },
  { name: 'Coqui', description: '开源语音合成', category: 'audio', url: 'https://github.com/coqui-ai/TTS', pricing: 'free', tags: ['开源', '语音', 'TTS'] },
  { name: 'Piper', description: '轻量级本地 TTS', category: 'audio', url: 'https://github.com/rhasspy/piper', pricing: 'free', tags: ['开源', '本地', '轻量'] },
  { name: 'XTTS', description: '高质量语音克隆', category: 'audio', url: 'https://github.com/coqui-ai/TTS', pricing: 'free', tags: ['开源', '语音克隆', '高质量'] },
  { name: 'Fish Speech', description: '开源中文 TTS', category: 'audio', url: 'https://github.com/fishaudio/fish-speech', pricing: 'free', tags: ['开源', '中文', 'TTS'] },
  { name: 'ChatTTS', description: '开源对话式 TTS', category: 'audio', url: 'https://github.com/2noise/ChatTTS', pricing: 'free', tags: ['开源', '中文', '对话'] },
  { name: 'GPT-SoVITS', description: '语音克隆工具', category: 'audio', url: 'https://github.com/RVC-Boss/GPT-SoVITS', pricing: 'free', tags: ['开源', '语音克隆', '中文'] },
  { name: 'RVC', description: '实时语音转换', category: 'audio', url: 'https://github.com/RVC-Project/Retrieval-based-Voice-Conversion', pricing: 'free', tags: ['开源', '变声', '实时'] },
  { name: 'Adobe Podcast', description: 'AI 音频增强', category: 'audio', url: 'https://podcast.adobe.com', pricing: 'free', tags: ['Adobe', '音频增强', '播客'] },
  { name: 'Krisp', description: 'AI 降噪', category: 'audio', url: 'https://krisp.ai', pricing: 'free_paid', tags: ['降噪', '会议', '通话'] },
  { name: 'NVIDIA Broadcast', description: 'AI 音视频增强', category: 'audio', url: 'https://www.nvidia.com/broadcast', pricing: 'free', tags: ['NVIDIA', '降噪', '虚拟背景'] },
  { name: 'iZotope RX', description: '专业音频修复', category: 'audio', url: 'https://www.izotope.com/rx', pricing: 'paid', tags: ['音频修复', '专业', '后期'] },
  { name: 'Auphonic', description: '自动音频后期', category: 'audio', url: 'https://auphonic.com', pricing: 'free_paid', tags: ['音频后期', '播客', '自动'] },
  { name: '天工音乐', description: '昆仑万维的 AI 音乐', category: 'audio', url: 'https://www.tiangong.cn/music', pricing: 'free', tags: ['天工', '音乐', '中文'] },
  { name: '网易天音', description: '网易的 AI 音乐', category: 'audio', url: 'https://tianyin.163.com', pricing: 'free', tags: ['网易', '音乐', '中文'] },
  { name: 'TME Studio', description: '腾讯音乐的 AI 工具', category: 'audio', url: 'https://y.qq.com/tmestudio', pricing: 'free', tags: ['腾讯', '音乐', '创作'] },
  { name: '讯飞智作', description: '科大讯飞的 AI 配音', category: 'audio', url: 'https://www.xfzhizuo.cn', pricing: 'free_paid', tags: ['讯飞', '配音', '中文'] },
  { name: '魔音工坊', description: '中文 AI 配音平台', category: 'audio', url: 'https://www.moyin.com', pricing: 'free_paid', tags: ['配音', '中文', '视频'] },
  
  // 代码助手类 - 扩展
  { name: 'Devin', description: 'AI 软件工程师', category: 'code', url: 'https://www.cognition.ai', pricing: 'paid', tags: ['AI工程师', '自动编程', 'Cognition'] },
  { name: 'GitHub Copilot Chat', description: 'Copilot 的聊天功能', category: 'code', url: 'https://github.com/features/copilot', pricing: 'paid', tags: ['GitHub', '聊天', '编程'] },
  { name: 'Copilot Workspace', description: 'AI 驱动的开发环境', category: 'code', url: 'https://github.com/features/copilot', pricing: 'paid', tags: ['GitHub', '开发环境', 'AI'] },
  { name: 'Phind', description: 'AI 搜索引擎 for 开发者', category: 'code', url: 'https://www.phind.com', pricing: 'free_paid', tags: ['搜索', '开发', '问答'] },
  { name: 'Warp', description: 'AI 驱动的终端', category: 'code', url: 'https://www.warp.dev', pricing: 'free', tags: ['终端', '命令行', 'AI'] },
  { name: 'Fig', description: 'IDE 风格的终端自动补全', category: 'code', url: 'https://fig.io', pricing: 'free', tags: ['终端', '自动补全', 'IDE'] },
  { name: 'Raycast', description: 'AI 驱动的效率启动器', category: 'code', url: 'https://www.raycast.com', pricing: 'free', tags: ['启动器', '效率', 'AI'] },
  { name: 'Pieces', description: 'AI 代码片段管理', category: 'code', url: 'https://pieces.app', pricing: 'free', tags: ['代码片段', '管理', 'AI'] },
  { name: 'Mintlify', description: 'AI 文档生成', category: 'code', url: 'https://mintlify.com', pricing: 'free_paid', tags: ['文档', '生成', 'API'] },
  { name: 'ReadMe', description: 'API 文档平台', category: 'code', url: 'https://readme.com', pricing: 'free_paid', tags: ['API文档', '开发者', '平台'] },
  { name: 'Swagger', description: 'API 设计和文档', category: 'code', url: 'https://swagger.io', pricing: 'free', tags: ['API', '文档', '设计'] },
  { name: 'Postman', description: 'API 开发和测试平台', category: 'code', url: 'https://www.postman.com', pricing: 'free_paid', tags: ['API', '测试', '开发'] },
  { name: 'Hoppscotch', description: '开源 API 开发平台', category: 'code', url: 'https://hoppscotch.io', pricing: 'free', tags: ['开源', 'API', '测试'] },
  { name: 'Insomnia', description: 'API 客户端', category: 'code', url: 'https://insomnia.rest', pricing: 'free_paid', tags: ['API', '测试', '客户端'] },
  { name: 'Kite', description: 'AI 代码补全', category: 'code', url: 'https://www.kite.com', pricing: 'free', tags: ['代码补全', 'Python', 'AI'] },
  { name: 'IntelliCode', description: 'Visual Studio 的 AI 助手', category: 'code', url: 'https://visualstudio.microsoft.com/intellicode', pricing: 'free', tags: ['VisualStudio', '代码补全', '微软'] },
  { name: 'GitLens', description: 'VS Code Git 增强', category: 'code', url: 'https://gitlens.dev', pricing: 'free_paid', tags: ['Git', 'VSCode', '版本控制'] },
  { name: 'GitKraken', description: 'Git 客户端', category: 'code', url: 'https://www.gitkraken.com', pricing: 'free_paid', tags: ['Git', '客户端', '可视化'] },
  { name: 'Sourcery', description: 'Python 代码重构', category: 'code', url: 'https://sourcery.ai', pricing: 'free_paid', tags: ['Python', '重构', '代码质量'] },
  { name: 'DeepCode', description: 'AI 代码审查', category: 'code', url: 'https://www.deepcode.ai', pricing: 'free', tags: ['代码审查', '安全', 'Snyk'] },
  { name: 'SonarQube', description: '代码质量管理', category: 'code', url: 'https://www.sonarqube.org', pricing: 'free', tags: ['代码质量', '静态分析', '开源'] },
  { name: 'CodeClimate', description: '自动化代码审查', category: 'code', url: 'https://codeclimate.com', pricing: 'free_paid', tags: ['代码审查', '质量', 'CI'] },
  { name: 'Codacy', description: '自动化代码质量', category: 'code', url: 'https://www.codacy.com', pricing: 'free_paid', tags: ['代码质量', '分析', 'CI'] },
  { name: 'CodeRabbit', description: 'AI 代码审查', category: 'code', url: 'https://coderabbit.ai', pricing: 'free_paid', tags: ['代码审查', 'AI', 'PR'] },
  { name: 'What The Diff', description: 'AI PR 审查', category: 'code', url: 'https://whatthediff.ai', pricing: 'free_paid', tags: ['PR', '代码审查', 'GitHub'] },
  { name: 'Bito', description: 'AI 开发助手', category: 'code', url: 'https://bito.ai', pricing: 'free_paid', tags: ['开发助手', '代码生成', 'IDE'] },
  { name: 'AskCodi', description: 'AI 编程助手', category: 'code', url: 'https://www.askcodi.com', pricing: 'free_paid', tags: ['编程', '代码生成', 'IDE'] },
  { name: 'CodeWP', description: 'WordPress 代码 AI', category: 'code', url: 'https://codewp.ai', pricing: 'free_paid', tags: ['WordPress', '代码', 'PHP'] },
  { name: 'MarsCode', description: '字节跳动的 AI IDE', category: 'code', url: 'https://www.marscode.com', pricing: 'free', tags: ['字节', 'IDE', '编程'] },
  { name: 'CodeFuse', description: '蚂蚁集团的代码助手', category: 'code', url: 'https://codefuse.ai', pricing: 'free', tags: ['蚂蚁', '代码', '开源'] },
  { name: '文心快码', description: '百度的代码助手', category: 'code', url: 'https://comate.baidu.com', pricing: 'free', tags: ['百度', '代码', '中文'] },
  { name: '通义灵码', description: '阿里的代码助手', category: 'code', url: 'https://tongyi.aliyun.com/lingma', pricing: 'free', tags: ['阿里', '代码', '中文'] },
  { name: 'iFlyCode', description: '讯飞的代码助手', category: 'code', url: 'https://iflycode.xfyun.cn', pricing: 'free', tags: ['讯飞', '代码', '中文'] },
  { name: 'Fitten Code', description: '非十科技的代码助手', category: 'code', url: 'https://code.fittentech.com', pricing: 'free', tags: ['代码', '中文', '免费'] },
  { name: '腾讯云 AI 代码助手', description: '腾讯云的编程助手', category: 'code', url: 'https://cloud.tencent.com/product/acc', pricing: 'free', tags: ['腾讯', '代码', '云'] },
  { name: '华为云 CodeArts', description: '华为云的 DevOps 平台', category: 'code', url: 'https://www.huaweicloud.com/codearts', pricing: 'free_paid', tags: ['华为', 'DevOps', '云'] },
  { name: '码上飞', description: 'AI 代码生成平台', category: 'code', url: 'https://www.codesky.ai', pricing: 'free', tags: ['代码生成', '中文', '平台'] },
  { name: '智谱代码', description: '智谱的代码助手', category: 'code', url: 'https://chatglm.cn/code', pricing: 'free', tags: ['智谱', '代码', '中文'] },
  
  // 写作助手类 - 扩展
  { name: 'Notion AI', description: 'Notion 的 AI 写作助手', category: 'writing', url: 'https://www.notion.so/product/ai', pricing: 'paid', tags: ['Notion', '写作', '笔记'] },
  { name: 'Grammarly', description: 'AI 写作辅助和语法检查', category: 'writing', url: 'https://www.grammarly.com', pricing: 'free_paid', tags: ['语法', '写作', '校对'] },
  { name: 'QuillBot', description: 'AI 改写和润色', category: 'writing', url: 'https://quillbot.com', pricing: 'free_paid', tags: ['改写', '润色', '学术'] },
  { name: 'Wordtune', description: 'AI 写作优化', category: 'writing', url: 'https://www.wordtune.com', pricing: 'free_paid', tags: ['写作', '优化', '改写'] },
  { name: 'ProWritingAid', description: '写作分析和改进', category: 'writing', url: 'https://prowritingaid.com', pricing: 'free_paid', tags: ['写作', '分析', '改进'] },
  { name: 'Hemingway Editor', description: '写作清晰度分析', category: 'writing', url: 'https://hemingwayapp.com', pricing: 'free_paid', tags: ['写作', '清晰度', '简洁'] },
  { name: 'LanguageTool', description: '开源语法检查', category: 'writing', url: 'https://languagetool.org', pricing: 'free_paid', tags: ['开源', '语法', '多语言'] },
  { name: 'Sudowrite', description: 'AI 小说写作助手', category: 'writing', url: 'https://www.sudowrite.com', pricing: 'paid', tags: ['小说', '创意', '写作'] },
  { name: 'NovelAI', description: 'AI 故事和图像生成', category: 'writing', url: 'https://novelai.net', pricing: 'paid', tags: ['小说', '故事', '图像'] },
  { name: 'Rytr', description: 'AI 内容写作', category: 'writing', url: 'https://rytr.me', pricing: 'free_paid', tags: ['内容', '营销', '写作'] },
  { name: 'Writesonic', description: 'AI 营销文案', category: 'writing', url: 'https://writesonic.com', pricing: 'free_paid', tags: ['营销', '文案', 'SEO'] },
  { name: 'Anyword', description: 'AI 营销文案优化', category: 'writing', url: 'https://anyword.com', pricing: 'paid', tags: ['营销', '文案', '预测'] },
  { name: 'Copymatic', description: 'AI 内容生成', category: 'writing', url: 'https://copymatic.ai', pricing: 'paid', tags: ['内容', '生成', '营销'] },
  { name: 'TextCortex', description: 'AI 写作助手', category: 'writing', url: 'https://textcortex.com', pricing: 'free_paid', tags: ['写作', '助手', '多语言'] },
  { name: 'HyperWrite', description: 'AI 写作和研究', category: 'writing', url: 'https://www.hyperwriteai.com', pricing: 'free_paid', tags: ['写作', '研究', '浏览器'] },
  { name: 'Frase', description: 'SEO 内容优化', category: 'writing', url: 'https://www.frase.io', pricing: 'paid', tags: ['SEO', '内容', '研究'] },
  { name: 'Surfer SEO', description: 'SEO 内容编辑器', category: 'writing', url: 'https://surferseo.com', pricing: 'paid', tags: ['SEO', '内容', '排名'] },
  { name: 'Clearscope', description: 'SEO 内容优化', category: 'writing', url: 'https://www.clearscope.io', pricing: 'paid', tags: ['SEO', '内容', '优化'] },
  { name: 'MarketMuse', description: 'AI 内容策略', category: 'writing', url: 'https://www.marketmuse.com', pricing: 'paid', tags: ['内容策略', 'SEO', 'AI'] },
  { name: 'Dashword', description: '内容简报和优化', category: 'writing', url: 'https://dashword.com', pricing: 'paid', tags: ['内容', '简报', 'SEO'] },
  { name: 'Writer', description: '企业级 AI 写作', category: 'writing', url: 'https://writer.com', pricing: 'paid', tags: ['企业', '写作', '品牌'] },
  { name: 'Typeface', description: '企业内容创作', category: 'writing', url: 'https://www.typeface.ai', pricing: 'paid', tags: ['企业', '内容', '品牌'] },
  { name: 'Jasper Brand Voice', description: '品牌声音 AI', category: 'writing', url: 'https://www.jasper.ai', pricing: 'paid', tags: ['品牌', '声音', '营销'] },
  { name: 'Copy.ai', description: '营销文案 AI', category: 'writing', url: 'https://www.copy.ai', pricing: 'free_paid', tags: ['营销', '文案', 'AI'] },
  { name: 'ContentBot', description: 'AI 内容自动化', category: 'writing', url: 'https://contentbot.ai', pricing: 'paid', tags: ['内容', '自动化', '博客'] },
  { name: 'Article Forge', description: 'AI 文章生成', category: 'writing', url: 'https://www.articleforge.com', pricing: 'paid', tags: ['文章', '生成', 'SEO'] },
  { name: 'WordAI', description: '文章改写工具', category: 'writing', url: 'https://wordai.com', pricing: 'paid', tags: ['改写', '文章', 'SEO'] },
  { name: 'Spin Rewriter', description: '文章重写工具', category: 'writing', url: 'https://www.spinrewriter.com', pricing: 'paid', tags: ['重写', 'SEO', '文章'] },
  { name: 'Chimp Rewriter', description: '文章重写软件', category: 'writing', url: 'https://chimprewriter.com', pricing: 'paid', tags: ['重写', 'SEO', '文章'] },
  { name: '秘塔写作猫', description: '中文 AI 写作', category: 'writing', url: 'https://www.xiezuocat.com', pricing: 'free_paid', tags: ['中文', '写作', '校对'] },
  { name: '笔灵 AI', description: '中文 AI 写作助手', category: 'writing', url: 'https://www.biling.cn', pricing: 'free_paid', tags: ['中文', '写作', '论文'] },
  { name: '讯飞语记', description: '语音转文字写作', category: 'writing', url: 'https://www.iflynote.com', pricing: 'free_paid', tags: ['讯飞', '语音', '笔记'] },
  { name: 'WPS AI', description: 'WPS 的 AI 功能', category: 'writing', url: 'https://www.wps.cn/ai', pricing: 'free_paid', tags: ['WPS', '办公', '中文'] },
  { name: '腾讯文档 AI', description: '腾讯文档的智能功能', category: 'writing', url: 'https://docs.qq.com', pricing: 'free', tags: ['腾讯', '文档', '协作'] },
  { name: '石墨文档 AI', description: '石墨文档的 AI 功能', category: 'writing', url: 'https://shimo.im', pricing: 'free_paid', tags: ['石墨', '文档', '协作'] },
  { name: '飞书智能伙伴', description: '飞书的 AI 助手', category: 'writing', url: 'https://www.feishu.cn', pricing: 'free_paid', tags: ['飞书', '办公', '协作'] },
  { name: '钉钉魔法棒', description: '钉钉的 AI 助手', category: 'writing', url: 'https://www.dingtalk.com', pricing: 'free', tags: ['钉钉', '办公', '阿里'] },
  { name: '百度文库 AI', description: '百度文库的智能功能', category: 'writing', url: 'https://wenku.baidu.com', pricing: 'free_paid', tags: ['百度', '文库', '文档'] },
  { name: '知网 AI', description: '知网的智能功能', category: 'writing', url: 'https://www.cnki.net', pricing: 'paid', tags: ['知网', '学术', '论文'] },
  { name: '万方 AI', description: '万方数据的智能功能', category: 'writing', url: 'https://www.wanfangdata.com.cn', pricing: 'paid', tags: ['万方', '学术', '论文'] },
  { name: '维普 AI', description: '维普的智能功能', category: 'writing', url: 'https://www.cqvip.com', pricing: 'paid', tags: ['维普', '学术', '论文'] },
  
  // 搜索引擎类 - 扩展
  { name: 'Kimi 搜索', description: 'Kimi 的联网搜索功能', category: 'search', url: 'https://kimi.moonshot.cn', pricing: 'free', tags: ['搜索', '中文', '长文本'] },
  { name: '秘塔 AI 搜索', description: '结构化搜索结果', category: 'search', url: 'https://metaso.cn', pricing: 'free', tags: ['搜索', '中文', '结构化'] },
  { name: '360 AI 搜索', description: '360 的 AI 搜索', category: 'search', url: 'https://ai.so.com', pricing: 'free', tags: ['搜索', '中文', '360'] },
  { name: '天工 AI 搜索', description: '天工的搜索功能', category: 'search', url: 'https://www.tiangong.cn', pricing: 'free', tags: ['搜索', '中文', '昆仑'] },
  { name: '博查 AI 搜索', description: '多模态 AI 搜索', category: 'search', url: 'https://bocha.ai', pricing: 'free', tags: ['搜索', '中文', '多模态'] },
  { name: 'Devv', description: '开发者搜索引擎', category: 'search', url: 'https://devv.ai', pricing: 'free', tags: ['搜索', '开发者', '代码'] },
  { name: 'Globe Explorer', description: '可视化知识探索', category: 'search', url: 'https://explorer.globe.engineer', pricing: 'free', tags: ['搜索', '可视化', '知识'] },
  { name: 'Consensus', description: 'AI 科研搜索', category: 'search', url: 'https://consensus.app', pricing: 'free_paid', tags: ['科研', '论文', '学术'] },
  { name: 'Elicit', description: 'AI 研究助手', category: 'search', url: 'https://elicit.org', pricing: 'free_paid', tags: ['研究', '论文', '学术'] },
  { name: 'Semantic Scholar', description: '学术搜索引擎', category: 'search', url: 'https://www.semanticscholar.org', pricing: 'free', tags: ['学术', '论文', 'AI'] },
  { name: 'Connected Papers', description: '论文关系图谱', category: 'search', url: 'https://www.connectedpapers.com', pricing: 'free_paid', tags: ['论文', '图谱', '学术'] },
  { name: 'Research Rabbit', description: '文献发现工具', category: 'search', url: 'https://www.researchrabbit.ai', pricing: 'free', tags: ['文献', '学术', '发现'] },
  { name: 'Litmaps', description: '文献可视化', category: 'search', url: 'https://www.litmaps.com', pricing: 'free_paid', tags: ['文献', '可视化', '学术'] },
  { name: 'Scite', description: '智能引文分析', category: 'search', url: 'https://scite.ai', pricing: 'free_paid', tags: ['引文', '学术', '分析'] },
  { name: 'You.com Search', description: 'You.com 搜索', category: 'search', url: 'https://you.com', pricing: 'free', tags: ['搜索', '隐私', 'AI'] },
  { name: 'Neeva', description: '隐私搜索引擎', category: 'search', url: 'https://neeva.com', pricing: 'free_paid', tags: ['搜索', '隐私', '无广告'] },
  { name: 'Kagi', description: '付费搜索引擎', category: 'search', url: 'https://kagi.com', pricing: 'paid', tags: ['搜索', '付费', '无广告'] },
  { name: 'Wolfram Alpha', description: '计算知识引擎', category: 'search', url: 'https://www.wolframalpha.com', pricing: 'free_paid', tags: ['计算', '知识', '数学'] },
  { name: 'Exa', description: 'AI 原生搜索引擎', category: 'search', url: 'https://exa.ai', pricing: 'free_paid', tags: ['搜索', 'AI', '语义'] },
  { name: 'Glean', description: '企业搜索', category: 'search', url: 'https://www.glean.com', pricing: 'paid', tags: ['企业', '搜索', '知识'] },
  
  // 办公效率类 - 扩展
  { name: 'Microsoft Copilot', description: '微软 365 AI 助手', category: 'productivity', url: 'https://copilot.microsoft.com', pricing: 'paid', tags: ['微软', '办公', '365'] },
  { name: 'Gamma', description: 'AI 演示文稿生成', category: 'productivity', url: 'https://gamma.app', pricing: 'free_paid', tags: ['PPT', '演示', '生成'] },
  { name: 'Beautiful.ai', description: '智能演示文稿', category: 'productivity', url: 'https://www.beautiful.ai', pricing: 'paid', tags: ['PPT', '设计', '智能'] },
  { name: 'Tome', description: 'AI 故事叙述', category: 'productivity', url: 'https://tome.app', pricing: 'free_paid', tags: ['故事', '演示', 'AI'] },
  { name: 'Pitch', description: '现代演示软件', category: 'productivity', url: 'https://pitch.com', pricing: 'free_paid', tags: ['PPT', '协作', '设计'] },
  { name: 'SlidesAI', description: 'Google Slides AI', category: 'productivity', url: 'https://www.slidesai.io', pricing: 'free_paid', tags: ['Google', 'PPT', 'AI'] },
  { name: 'Plus AI', description: 'Google Slides 生成', category: 'productivity', url: 'https://www.plusdocs.com', pricing: 'paid', tags: ['Google', 'PPT', '生成'] },
  { name: 'Decktopus', description: 'AI 演示生成器', category: 'productivity', url: 'https://www.decktopus.com', pricing: 'paid', tags: ['PPT', '生成', '模板'] },
  { name: 'Presentations.ai', description: 'AI 演示创建', category: 'productivity', url: 'https://www.presentations.ai', pricing: 'free_paid', tags: ['PPT', 'AI', '快速'] },
  { name: 'Sendsteps', description: '交互式演示 AI', category: 'productivity', url: 'https://www.sendsteps.com', pricing: 'paid', tags: ['PPT', '交互', '演示'] },
  { name: 'ChatBA', description: '聊天生成 PPT', category: 'productivity', url: 'https://www.chatba.com', pricing: 'free_paid', tags: ['PPT', '聊天', '生成'] },
  { name: 'Motion', description: 'AI 日程管理', category: 'productivity', url: 'https://www.usemotion.com', pricing: 'paid', tags: ['日程', '管理', '自动化'] },
  { name: 'Reclaim.ai', description: '智能日程安排', category: 'productivity', url: 'https://reclaim.ai', pricing: 'free_paid', tags: ['日程', '日历', '智能'] },
  { name: 'Clockwise', description: '团队日程优化', category: 'productivity', url: 'https://www.getclockwise.com', pricing: 'free_paid', tags: ['日程', '团队', '优化'] },
  { name: 'Amie', description: 'AI 日历应用', category: 'productivity', url: 'https://amie.so', pricing: 'free', tags: ['日历', '待办', '邮件'] },
  { name: 'Sunsama', description: '每日计划助手', category: 'productivity', url: 'https://www.sunsama.com', pricing: 'paid', tags: ['计划', '待办', '日历'] },
  { name: 'Akiflow', description: '任务和日历整合', category: 'productivity', url: 'https://akiflow.com', pricing: 'paid', tags: ['任务', '日历', '整合'] },
  { name: 'Routine', description: '笔记和日历结合', category: 'productivity', url: 'https://www.routine.co', pricing: 'free', tags: ['笔记', '日历', '待办'] },
  { name: 'Mem.ai', description: 'AI 笔记助手', category: 'productivity', url: 'https://mem.ai', pricing: 'free_paid', tags: ['笔记', 'AI', '搜索'] },
  { name: 'Reflect', description: 'AI 笔记应用', category: 'productivity', url: 'https://reflect.app', pricing: 'paid', tags: ['笔记', 'AI', '思考'] },
  { name: 'Capacities', description: '对象型笔记', category: 'productivity', url: 'https://capacities.io', pricing: 'free_paid', tags: ['笔记', '对象', '知识'] },
  { name: 'Anytype', description: '本地优先笔记', category: 'productivity', url: 'https://anytype.io', pricing: 'free', tags: ['笔记', '本地', '隐私'] },
  { name: 'Affine', description: '开源 Notion 替代', category: 'productivity', url: 'https://affine.pro', pricing: 'free', tags: ['开源', '笔记', '白板'] },
  { name: 'AppFlowy', description: '开源笔记工具', category: 'productivity', url: 'https://www.appflowy.io', pricing: 'free', tags: ['开源', '笔记', 'Notion'] },
  { name: 'Logseq', description: '大纲式笔记', category: 'productivity', url: 'https://logseq.com', pricing: 'free', tags: ['大纲', '笔记', '本地'] },
  { name: 'Obsidian', description: '本地知识库', category: 'productivity', url: 'https://obsidian.md', pricing: 'free_paid', tags: ['笔记', '本地', '知识库'] },
  { name: 'Roam Research', description: '网络化笔记', category: 'productivity', url: 'https://roamresearch.com', pricing: 'paid', tags: ['笔记', '网络', '思考'] },
  { name: 'Craft', description: '精美文档工具', category: 'productivity', url: 'https://www.craft.do', pricing: 'free_paid', tags: ['文档', '设计', '苹果'] },
  { name: 'Bear', description: '优雅 Markdown 笔记', category: 'productivity', url: 'https://bear.app', pricing: 'free_paid', tags: ['笔记', 'Markdown', '苹果'] },
  { name: 'Ulysses', description: '专业写作应用', category: 'productivity', url: 'https://ulysses.app', pricing: 'paid', tags: ['写作', 'Markdown', '苹果'] },
  { name: 'Scrivener', description: '长篇写作工具', category: 'productivity', url: 'https://www.literatureandlatte.com/scrivener', pricing: 'paid', tags: ['写作', '长篇', '小说'] },
  { name: 'iA Writer', description: '专注写作应用', category: 'productivity', url: 'https://ia.net/writer', pricing: 'paid', tags: ['写作', '专注', 'Markdown'] },
  { name: 'Notion Calendar', description: 'Notion 日历', category: 'productivity', url: 'https://www.notion.so/product/calendar', pricing: 'free', tags: ['日历', 'Notion', '日程'] },
  { name: 'Cron', description: '现代日历应用', category: 'productivity', url: 'https://cron.com', pricing: 'free', tags: ['日历', '设计', '效率'] },
  { name: 'Calendly', description: '日程安排工具', category: 'productivity', url: 'https://calendly.com', pricing: 'free_paid', tags: ['日程', '会议', '预约'] },
  { name: 'When2meet', description: '简单日程协调', category: 'productivity', url: 'https://www.when2meet.com', pricing: 'free', tags: ['日程', '协调', '简单'] },
  { name: 'Doodle', description: '会议时间协调', category: 'productivity', url: 'https://doodle.com', pricing: 'free_paid', tags: ['会议', '日程', '投票'] },
  { name: 'Loom', description: '视频消息工具', category: 'productivity', url: 'https://www.loom.com', pricing: 'free_paid', tags: ['视频', '消息', '异步'] },
  { name: 'Loom AI', description: 'Loom 的 AI 功能', category: 'productivity', url: 'https://www.loom.com/ai', pricing: 'paid', tags: ['视频', 'AI', '摘要'] },
  { name: 'Fireflies.ai', description: '会议记录 AI', category: 'productivity', url: 'https://fireflies.ai', pricing: 'free_paid', tags: ['会议', '记录', '转录'] },
  { name: 'Otter.ai', description: '实时转录工具', category: 'productivity', url: 'https://otter.ai', pricing: 'free_paid', tags: ['转录', '会议', '实时'] },
  { name: 'Fathom', description: '会议摘要 AI', category: 'productivity', url: 'https://fathom.video', pricing: 'free', tags: ['会议', '摘要', '免费'] },
  { name: 'tl;dv', description: '会议录制和摘要', category: 'productivity', url: 'https://tldv.io', pricing: 'free_paid', tags: ['会议', '录制', '摘要'] },
  { name: 'Grain', description: '会议洞察平台', category: 'productivity', url: 'https://grain.com', pricing: 'paid', tags: ['会议', '洞察', '销售'] },
  { name: 'Avoma', description: '会议智能平台', category: 'productivity', url: 'https://www.avoma.com', pricing: 'paid', tags: ['会议', '智能', '销售'] },
  { name: 'Chorus.ai', description: '对话智能平台', category: 'productivity', url: 'https://www.chorus.ai', pricing: 'paid', tags: ['销售', '对话', '分析'] },
  { name: 'Gong', description: '收入智能平台', category: 'productivity', url: 'https://www.gong.io', pricing: 'paid', tags: ['销售', '收入', '分析'] },
  { name: 'Wingman', description: '实时销售助手', category: 'productivity', url: 'https://www.wingman.com', pricing: 'paid', tags: ['销售', '实时', '助手'] },
  { name: 'Clari', description: '收入运营平台', category: 'productivity', url: 'https://www.clari.com', pricing: 'paid', tags: ['收入', '预测', '销售'] },
  { name: 'Outreach', description: '销售参与平台', category: 'productivity', url: 'https://www.outreach.io', pricing: 'paid', tags: ['销售', '参与', '自动化'] },
  { name: 'Salesloft', description: '销售参与平台', category: 'productivity', url: 'https://salesloft.com', pricing: 'paid', tags: ['销售', '参与', '邮件'] },
  { name: 'Apollo.io', description: '销售智能平台', category: 'productivity', url: 'https://apollo.io', pricing: 'free_paid', tags: ['销售', '线索', '数据'] },
  { name: 'ZoomInfo', description: 'B2B 数据平台', category: 'productivity', url: 'https://www.zoominfo.com', pricing: 'paid', tags: ['B2B', '数据', '销售'] },
  { name: 'Lusha', description: '联系人数据平台', category: 'productivity', url: 'https://www.lusha.com', pricing: 'free_paid', tags: ['联系人', '数据', '销售'] },
  { name: 'Hunter.io', description: '邮箱查找工具', category: 'productivity', url: 'https://hunter.io', pricing: 'free_paid', tags: ['邮箱', '查找', '验证'] },
  { name: 'Snov.io', description: '邮箱查找和验证', category: 'productivity', url: 'https://snov.io', pricing: 'free_paid', tags: ['邮箱', '查找', '验证'] },
  { name: 'NeverBounce', description: '邮箱验证服务', category: 'productivity', url: 'https://neverbounce.com', pricing: 'paid', tags: ['邮箱', '验证', '清洗'] },
  { name: 'ZeroBounce', description: '邮箱验证平台', category: 'productivity', url: 'https://www.zerobounce.net', pricing: 'free_paid', tags: ['邮箱', '验证', 'API'] },
  { name: 'Clearbit', description: 'B2B 数据丰富', category: 'productivity', url: 'https://clearbit.com', pricing: 'paid', tags: ['B2B', '数据', '丰富'] },
  { name: 'FullContact', description: '联系人数据平台', category: 'productivity', url: 'https://www.fullcontact.com', pricing: 'paid', tags: ['联系人', '数据', 'API'] },
  { name: 'Rapportive', description: 'LinkedIn 邮箱插件', category: 'productivity', url: 'https://rapportive.com', pricing: 'free', tags: ['LinkedIn', '邮箱', '插件'] },
  { name: 'Superhuman', description: '极速邮件客户端', category: 'productivity', url: 'https://superhuman.com', pricing: 'paid', tags: ['邮件', '快速', '效率'] },
  { name: 'Spark', description: '智能邮件应用', category: 'productivity', url: 'https://sparkmailapp.com', pricing: 'free_paid', tags: ['邮件', '智能', '分类'] },
  { name: 'Hey', description: '重新设计的邮件', category: 'productivity', url: 'https://www.hey.com', pricing: 'paid', tags: ['邮件', '重新设计', 'Basecamp'] },
  { name: 'Shortwave', description: 'AI 邮件客户端', category: 'productivity', url: 'https://www.shortwave.com', pricing: 'free_paid', tags: ['邮件', 'AI', 'Gmail'] },
  { name: 'Mailbutler', description: '邮件效率插件', category: 'productivity', url: 'https://www.mailbutler.io', pricing: 'free_paid', tags: ['邮件', '插件', '效率'] },
  { name: 'Boomerang', description: '邮件调度工具', category: 'productivity', url: 'https://www.boomeranggmail.com', pricing: 'free_paid', tags: ['邮件', '调度', '跟进'] },
  { name: 'FollowUpThen', description: '简单邮件提醒', category: 'productivity', url: 'https://www.followupthen.com', pricing: 'free_paid', tags: ['邮件', '提醒', '简单'] },
  { name: 'SaneBox', description: '邮件过滤服务', category: 'productivity', url: 'https://www.sanebox.com', pricing: 'paid', tags: ['邮件', '过滤', '整理'] },
  { name: 'Clean Email', description: '邮件清理工具', category: 'productivity', url: 'https://clean.email', pricing: 'free_paid', tags: ['邮件', '清理', '批量'] },
  { name: 'Unroll.Me', description: '邮件退订工具', category: 'productivity', url: 'https://unroll.me', pricing: 'free', tags: ['邮件', '退订', '整理'] },
  { name: 'Leave Me Alone', description: '邮件退订服务', category: 'productivity', url: 'https://leavemealone.app', pricing: 'free_paid', tags: ['邮件', '退订', '隐私'] },
  { name: 'Mailchimp', description: '邮件营销平台', category: 'productivity', url: 'https://mailchimp.com', pricing: 'free_paid', tags: ['邮件营销', '自动化', '分析'] },
  { name: 'ConvertKit', description: '创作者邮件平台', category: 'productivity', url: 'https://convertkit.com', pricing: 'free_paid', tags: ['邮件', '创作者', '自动化'] },
  { name: 'Beehiiv', description: '新闻通讯平台', category: 'productivity', url: 'https://www.beehiiv.com', pricing: 'free_paid', tags: ['新闻通讯', '邮件', '增长'] },
  { name: 'Substack', description: '付费 newsletter 平台', category: 'productivity', url: 'https://substack.com', pricing: 'free', tags: ['newsletter', '付费', '写作'] },
  { name: 'Ghost', description: '独立出版平台', category: 'productivity', url: 'https://ghost.org', pricing: 'paid', tags: ['博客', 'newsletter', '开源'] },
  { name: 'Buttondown', description: '简单邮件通讯', category: 'productivity', url: 'https://buttondown.email', pricing: 'free_paid', tags: ['邮件', 'newsletter', '简单'] },
  { name: 'MailerLite', description: '邮件营销工具', category: 'productivity', url: 'https://www.mailerlite.com', pricing: 'free_paid', tags: ['邮件营销', '自动化', '着陆页'] },
  { name: 'Klaviyo', description: '电商邮件营销', category: 'productivity', url: 'https://www.klaviyo.com', pricing: 'free_paid', tags: ['电商', '邮件', 'SMS'] },
  { name: 'ActiveCampaign', description: '营销自动化', category: 'productivity', url: 'https://www.activecampaign.com', pricing: 'paid', tags: ['营销', '自动化', 'CRM'] },
  { name: 'HubSpot', description: '营销销售平台', category: 'productivity', url: 'https://www.hubspot.com', pricing: 'free_paid', tags: ['营销', 'CRM', '销售'] },
  { name: 'Pipedrive', description: '销售 CRM', category: 'productivity', url: 'https://www.pipedrive.com', pricing: 'paid', tags: ['CRM', '销售', '管道'] },
  { name: 'Salesforce', description: '企业 CRM', category: 'productivity', url: 'https://www.salesforce.com', pricing: 'paid', tags: ['CRM', '企业', '云'] },
  { name: 'Zoho CRM', description: '性价比 CRM', category: 'productivity', url: 'https://www.zoho.com/crm', pricing: 'free_paid', tags: ['CRM', '性价比', '全套'] },
  { name: 'Freshsales', description: '现代 CRM', category: 'productivity', url: 'https://www.freshworks.com/crm', pricing: 'free_paid', tags: ['CRM', '现代', '易用'] },
  { name: 'Monday.com', description: '工作管理平台', category: 'productivity', url: 'https://monday.com', pricing: 'free_paid', tags: ['项目', '管理', '可视化'] },
  { name: 'Asana', description: '项目和任务管理', category: 'productivity', url: 'https://asana.com', pricing: 'free_paid', tags: ['项目', '任务', '协作'] },
  { name: 'ClickUp', description: '全能工作平台', category: 'productivity', url: 'https://clickup.com', pricing: 'free_paid', tags: ['项目', '文档', '全能'] },
  { name: 'Notion Projects', description: 'Notion 项目管理', category: 'productivity', url: 'https://www.notion.so', pricing: 'free_paid', tags: ['项目', 'Notion', '数据库'] },
  { name: 'Linear', description: '现代 issue 跟踪', category: 'productivity', url: 'https://linear.app', pricing: 'free', tags: ['issue', '敏捷', '设计'] },
  { name: 'Height', description: 'AI 项目管理', category: 'productivity', url: 'https://height.app', pricing: 'free_paid', tags: ['项目', 'AI', '自动化'] },
  { name: 'Shortcut', description: '项目管理工具', category: 'productivity', url: 'https://shortcut.com', pricing: 'free_paid', tags: ['项目', '敏捷', '开发'] },
  { name: 'Clubhouse', description: '项目管理平台', category: 'productivity', url: 'https://clubhouse.io', pricing: 'free_paid', tags: ['项目', '敏捷', '故事'] },
  { name: 'Jira', description: '敏捷项目管理', category: 'productivity', url: 'https://www.atlassian.com/software/jira', pricing: 'free_paid', tags: ['敏捷', '开发', 'Atlassian'] },
  { name: 'Confluence', description: '团队文档协作', category: 'productivity', url: 'https://www.atlassian.com/software/confluence', pricing: 'free_paid', tags: ['文档', '协作', 'Atlassian'] },
  { name: 'Trello', description: '看板项目管理', category: 'productivity', url: 'https://trello.com', pricing: 'free_paid', tags: ['看板', '简单', 'Atlassian'] },
  { name: 'Basecamp', description: '简单项目管理', category: 'productivity', url: 'https://basecamp.com', pricing: 'paid', tags: ['项目', '简单', '远程'] },
  { name: 'Teamwork', description: '项目管理平台', category: 'productivity', url: 'https://www.teamwork.com', pricing: 'free_paid', tags: ['项目', '客户', '计费'] },
  { name: 'Wrike', description: '企业项目管理', category: 'productivity', url: 'https://www.wrike.com', pricing: 'free_paid', tags: ['项目', '企业', '报告'] },
  { name: 'Smartsheet', description: '电子表格式项目', category: 'productivity', url: 'https://www.smartsheet.com', pricing: 'paid', tags: ['项目', '表格', '企业'] },
  { name: 'Airtable', description: '数据库式表格', category: 'productivity', url: 'https://www.airtable.com', pricing: 'free_paid', tags: ['数据库', '表格', '无代码'] },
  { name: 'Coda', description: '文档和表格结合', category: 'productivity', url: 'https://coda.io', pricing: 'free_paid', tags: ['文档', '表格', '自动化'] },
  { name: 'Softr', description: '无代码应用构建', category: 'productivity', url: 'https://www.softr.io', pricing: 'free_paid', tags: ['无代码', '应用', 'Airtable'] },
  { name: 'Glide', description: '从表格构建应用', category: 'productivity', url: 'https://www.glideapps.com', pricing: 'free_paid', tags: ['无代码', '应用', '移动'] },
  { name: 'Bubble', description: '无代码 Web 应用', category: 'productivity', url: 'https://bubble.io', pricing: 'free_paid', tags: ['无代码', 'Web', '应用'] },
  { name: 'Webflow', description: '可视化 Web 开发', category: 'productivity', url: 'https://webflow.com', pricing: 'free_paid', tags: ['无代码', 'Web', '设计'] },
  { name: 'Framer', description: '设计和发布网站', category: 'productivity', url: 'https://www.framer.com', pricing: 'free_paid', tags: ['设计', '网站', '发布'] },
  { name: 'Figma', description: '协作设计工具', category: 'productivity', url: 'https://www.figma.com', pricing: 'free_paid', tags: ['设计', '协作', 'UI'] },
  { name: 'Figma AI', description: 'Figma 的 AI 功能', category: 'productivity', url: 'https://www.figma.com/ai', pricing: 'paid', tags: ['设计', 'AI', 'UI'] },
  { name: 'Sketch', description: 'Mac 设计工具', category: 'productivity', url: 'https://www.sketch.com', pricing: 'paid', tags: ['设计', 'Mac', 'UI'] },
  { name: 'Adobe XD', description: 'Adobe 设计工具', category: 'productivity', url: 'https://www.adobe.com/products/xd', pricing: 'free', tags: ['设计', 'Adobe', '原型'] },
  { name: 'InVision', description: '设计协作平台', category: 'productivity', url: 'https://www.invisionapp.com', pricing: 'free_paid', tags: ['设计', '原型', '协作'] },
  { name: 'Miro', description: '在线白板协作', category: 'productivity', url: 'https://miro.com', pricing: 'free_paid', tags: ['白板', '协作', '可视化'] },
  { name: 'Mural', description: '团队协作白板', category: 'productivity', url: 'https://www.mural.co', pricing: 'free_paid', tags: ['白板', '团队', '工作坊'] },
  { name: 'FigJam', description: 'Figma 白板', category: 'productivity', url: 'https://www.figma.com/figjam', pricing: 'free', tags: ['白板', 'Figma', '协作'] },
  { name: 'Whimsical', description: '流程图和线框', category: 'productivity', url: 'https://whimsical.com', pricing: 'free_paid', tags: ['流程图', '线框', '思维导图'] },
  { name: 'Lucidchart', description: '图表绘制工具', category: 'productivity', url: 'https://www.lucidchart.com', pricing: 'free_paid', tags: ['图表', '流程', '企业'] },
  { name: 'Draw.io', description: '免费图表工具', category: 'productivity', url: 'https://www.draw.io', pricing: 'free', tags: ['图表', '免费', '开源'] },
  { name: 'Excalidraw', description: '手绘风格白板', category: 'productivity', url: 'https://excalidraw.com', pricing: 'free', tags: ['白板', '手绘', '开源'] },
  { name: 'tldraw', description: '无限画布白板', category: 'productivity', url: 'https://www.tldraw.com', pricing: 'free', tags: ['白板', '无限', '开源'] },
  { name: 'Arc Browser', description: '现代 AI 浏览器', category: 'productivity', url: 'https://arc.net', pricing: 'free', tags: ['浏览器', 'AI', '现代'] },
  { name: 'SigmaOS', description: '工作浏览器', category: 'productivity', url: 'https://sigmaos.com', pricing: 'free_paid', tags: ['浏览器', '工作', 'Mac'] },
  { name: 'Sidekick', description: '工作应用浏览器', category: 'productivity', url: 'https://www.meetsidekick.com', pricing: 'free', tags: ['浏览器', '应用', '工作区'] },
  { name: 'Shift', description: '应用整合浏览器', category: 'productivity', url: 'https://tryshift.com', pricing: 'free_paid', tags: ['浏览器', '应用', '整合'] },
  { name: 'Station', description: '智能工作站', category: 'productivity', url: 'https://getstation.com', pricing: 'free', tags: ['工作站', '应用', '效率'] },
  { name: 'Rambox', description: '消息应用整合', category: 'productivity', url: 'https://rambox.app', pricing: 'free_paid', tags: ['消息', '整合', '多账户'] },
  { name: 'Franz', description: '消息应用整合', category: 'productivity', url: 'https://meetfranz.com', pricing: 'free', tags: ['消息', '整合', '开源'] },
  { name: 'Ferdi', description: 'Franz 分支', category: 'productivity', url: 'https://getferdi.com', pricing: 'free', tags: ['消息', '整合', '开源'] },
  { name: 'All-in-One Messenger', description: '消息整合应用', category: 'productivity', url: 'https://allinone.im', pricing: 'free', tags: ['消息', '整合', '简单'] },
  { name: 'IM+', description: '多协议消息', category: 'productivity', url: 'https://www.implus.net', pricing: 'free_paid', tags: ['消息', '多协议', 'Mac'] },
  { name: 'Texts', description: '统一消息应用', category: 'productivity', url: 'https://texts.com', pricing: 'paid', tags: ['消息', '统一', 'Mac'] },
  { name: 'Beeper', description: '多平台消息', category: 'productivity', url: 'https://www.beeper.com', pricing: 'free', tags: ['消息', '多平台', '整合'] },
  { name: 'Texts.com', description: '消息聚合', category: 'productivity', url: 'https://texts.com', pricing: 'paid', tags: ['消息', '聚合', 'Mac'] },
  { name: 'Slack', description: '团队通讯', category: 'productivity', url: 'https://slack.com', pricing: 'free_paid', tags: ['团队', '通讯', '协作'] },
  { name: 'Slack AI', description: 'Slack 的 AI 功能', category: 'productivity', url: 'https://slack.com/ai', pricing: 'paid', tags: ['Slack', 'AI', '摘要'] },
  { name: 'Microsoft Teams', description: '微软团队通讯', category: 'productivity', url: 'https://www.microsoft.com/teams', pricing: 'free_paid', tags: ['微软', '团队', '会议'] },
  { name: 'Discord', description: '社区通讯平台', category: 'productivity', url: 'https://discord.com', pricing: 'free', tags: ['社区', '语音', '游戏'] },
  { name: 'Telegram', description: '安全消息应用', category: 'productivity', url: 'https://telegram.org', pricing: 'free', tags: ['消息', '安全', '快速'] },
  { name: 'WhatsApp', description: '流行消息应用', category: 'productivity', url: 'https://www.whatsapp.com', pricing: 'free', tags: ['消息', '通话', 'Meta'] },
  { name: 'Signal', description: '隐私消息应用', category: 'productivity', url: 'https://signal.org', pricing: 'free', tags: ['隐私', '安全', '开源'] },
  { name: 'Element', description: '去中心化聊天', category: 'productivity', url: 'https://element.io', pricing: 'free', tags: ['去中心化', 'Matrix', '开源'] },
  { name: 'Matrix', description: '开放通讯协议', category: 'productivity', url: 'https://matrix.org', pricing: 'free', tags: ['协议', '开源', '去中心化'] },
  { name: 'Mattermost', description: '开源团队通讯', category: 'productivity', url: 'https://mattermost.com', pricing: 'free_paid', tags: ['开源', '团队', '自托管'] },
  { name: 'Rocket.Chat', description: '开源通讯平台', category: 'productivity', url: 'https://rocket.chat', pricing: 'free_paid', tags: ['开源', '通讯', '自托管'] },
  { name: 'Zulip', description: '话题式聊天', category: 'productivity', url: 'https://zulip.com', pricing: 'free', tags: ['话题', '开源', '组织'] },
  { name: ' Twist', description: '异步团队通讯', category: 'productivity', url: 'https://twist.com', pricing: 'free_paid', tags: ['异步', '团队', 'Doist'] },
  { name: ' Twist', description: '异步团队沟通', category: 'productivity', url: 'https://twist.com', pricing: 'free_paid', tags: ['异步', '团队', '沟通'] },
  
  // 设计工具类 - 扩展
  { name: 'Adobe Sensei', description: 'Adobe 的 AI 和机器学习平台', category: 'design', url: 'https://www.adobe.com/sensei', pricing: 'paid', tags: ['Adobe', 'AI', '创意'] },
  { name: 'Clipdrop', description: 'AI 图像编辑工具套件', category: 'design', url: 'https://clipdrop.co', pricing: 'free_paid', tags: ['图像编辑', 'AI', 'Stability'] },
  { name: 'Alpaca', description: 'Photoshop AI 插件', category: 'design', url: 'https://www.alpacaml.com', pricing: 'paid', tags: ['Photoshop', '插件', 'AI'] },
  { name: 'Astria', description: 'AI 图像生成和微调', category: 'design', url: 'https://www.astria.ai', pricing: 'paid', tags: ['图像生成', '微调', '定制'] },
  { name: 'BlueWillow', description: '免费的 AI 图像生成', category: 'design', url: 'https://www.bluewillow.ai', pricing: 'free', tags: ['图像生成', '免费', 'Discord'] },
  { name: 'Craiyon', description: '免费的 DALL-E Mini', category: 'design', url: 'https://www.craiyon.com', pricing: 'free', tags: ['图像生成', '免费', '简单'] },
  { name: 'DeepArt', description: '艺术风格迁移', category: 'design', url: 'https://deepart.io', pricing: 'paid', tags: ['艺术', '风格迁移', '滤镜'] },
  { name: 'Deep Dream Generator', description: 'Deep Dream 图像生成', category: 'design', url: 'https://deepdreamgenerator.com', pricing: 'free_paid', tags: ['DeepDream', '艺术', '迷幻'] },
  { name: 'Designs.ai', description: 'AI 设计工具套件', category: 'design', url: 'https://designs.ai', pricing: 'paid', tags: ['设计', 'Logo', '视频'] },
  { name: 'DiffusionBee', description: 'Mac 本地 Stable Diffusion', category: 'design', url: 'https://diffusionbee.com', pricing: 'free', tags: ['Mac', '本地', 'StableDiffusion'] },
  { name: 'DreamStudio', description: 'Stability AI 官方平台', category: 'design', url: 'https://dreamstudio.ai', pricing: 'paid', tags: ['Stability', '官方', '图像生成'] },
  { name: 'Facet', description: 'AI 图像编辑', category: 'design', url: 'https://facet.ai', pricing: 'free_paid', tags: ['图像编辑', 'AI', '协作'] },
  { name: 'GetIMG', description: 'AI 图像生成和编辑', category: 'design', url: 'https://getimg.ai', pricing: 'free_paid', tags: ['图像生成', '编辑', 'API'] },
  { name: 'Hotpot.ai', description: 'AI 图像和写作工具', category: 'design', url: 'https://hotpot.ai', pricing: 'free_paid', tags: ['图像', '写作', '模板'] },
  { name: 'Hypotenuse AI', description: 'AI 图像和文案', category: 'design', url: 'https://www.hypotenuse.ai', pricing: 'paid', tags: ['图像', '文案', '电商'] },
  { name: 'Jasper Art', description: 'Jasper 的 AI 图像生成', category: 'design', url: 'https://www.jasper.ai/art', pricing: 'paid', tags: ['Jasper', '图像', '营销'] },
  { name: 'Krea', description: '实时 AI 图像生成', category: 'design', url: 'https://www.krea.ai', pricing: 'free_paid', tags: ['实时', '图像生成', '编辑'] },
  { name: 'Lexica', description: 'Stable Diffusion 搜索引擎', category: 'design', url: 'https://lexica.art', pricing: 'free', tags: ['搜索', 'StableDiffusion', '灵感'] },
  { name: 'Magic Studio', description: 'AI 图像编辑工具', category: 'design', url: 'https://magicstudio.com', pricing: 'free_paid', tags: ['图像编辑', '背景移除', 'AI'] },
  { name: 'Neural.love', description: 'AI 图像和视频增强', category: 'design', url: 'https://neural.love', pricing: 'free_paid', tags: ['增强', '图像', '视频'] },
  { name: 'NightCafe Studio', description: 'AI 艺术生成社区', category: 'design', url: 'https://nightcafe.studio', pricing: 'free_paid', tags: ['艺术', '社区', 'NFT'] },
  { name: 'OpenArt', description: 'AI 图像生成和编辑', category: 'design', url: 'https://openart.ai', pricing: 'free_paid', tags: ['图像生成', '编辑', '模型'] },
  { name: 'PhotoRoom', description: 'AI 产品照片编辑', category: 'design', url: 'https://www.photoroom.com', pricing: 'free_paid', tags: ['产品', '背景移除', '电商'] },
  { name: 'PicSo', description: 'AI 艺术生成应用', category: 'design', url: 'https://picso.ai', pricing: 'free_paid', tags: ['艺术', '移动', 'NFT'] },
  { name: 'PixAI', description: '动漫风格 AI 图像', category: 'design', url: 'https://pixai.art', pricing: 'free_paid', tags: ['动漫', '图像生成', '艺术'] },
  { name: 'Playform', description: 'AI 艺术创作平台', category: 'design', url: 'https://playform.io', pricing: 'paid', tags: ['艺术', '创作', '实验'] },
  { name: 'Pollinations', description: '免费 AI 图像生成', category: 'design', url: 'https://pollinations.ai', pricing: 'free', tags: ['免费', '开源', '图像生成'] },
  { name: 'Scenario', description: '游戏资产生成', category: 'design', url: 'https://www.scenario.com', pricing: 'paid', tags: ['游戏', '资产', '定制模型'] },
  { name: 'Simplified', description: 'AI 设计和营销平台', category: 'design', url: 'https://simplified.com', pricing: 'free_paid', tags: ['设计', '营销', '协作'] },
  { name: 'StarryAI', description: 'AI 艺术生成', category: 'design', url: 'https://starryai.com', pricing: 'free_paid', tags: ['艺术', '移动', 'NFT'] },
  { name: 'Supermeme', description: 'AI 表情包生成', category: 'design', url: 'https://www.supermeme.ai', pricing: 'free_paid', tags: ['表情包', '营销', '社交媒体'] },
  { name: 'This Person Does Not Exist', description: '随机生成人脸', category: 'design', url: 'https://thispersondoesnotexist.com', pricing: 'free', tags: ['人脸', '随机', 'GAN'] },
  { name: 'Vectorizer.AI', description: '位图转矢量', category: 'design', url: 'https://vectorizer.ai', pricing: 'free_paid', tags: ['矢量', '转换', 'SVG'] },
  { name: 'VanceAI', description: 'AI 图像增强', category: 'design', url: 'https://vanceai.com', pricing: 'paid', tags: ['增强', '放大', '修复'] },
  { name: 'Visme', description: '视觉内容设计', category: 'design', url: 'https://www.visme.co', pricing: 'free_paid', tags: ['设计', '信息图', '演示'] },
  { name: 'Waifu Labs', description: '动漫头像生成', category: 'design', url: 'https://waifulabs.com', pricing: 'free', tags: ['动漫', '头像', '游戏'] },
  { name: 'ZMO.AI', description: 'AI 图像生成和编辑', category: 'design', url: 'https://www.zmo.ai', pricing: 'free_paid', tags: ['图像生成', '编辑', '虚拟模特'] },
  { name: '佐糖', description: 'AI 图像处理工具', category: 'design', url: 'https://picwish.cn', pricing: 'free_paid', tags: ['图像处理', '抠图', '修复'] },
  { name: '稿定抠图', description: 'AI 在线抠图', category: 'design', url: 'https://www.gaoding.com/koutu', pricing: 'free_paid', tags: ['抠图', '在线', '设计'] },
  { name: '比格设计', description: '在线设计工具', category: 'design', url: 'https://bigesj.com', pricing: 'free_paid', tags: ['设计', '海报', '新媒体'] },
  { name: '图怪兽', description: '在线设计神器', category: 'design', url: 'https://818ps.com', pricing: 'free_paid', tags: ['设计', '模板', '简单'] },
  { name: '懒设计', description: '在线平面设计', category: 'design', url: 'https://www.fotor.com.cn', pricing: 'free_paid', tags: ['设计', '海报', '编辑'] },
  { name: '易企秀', description: 'H5 页面制作', category: 'design', url: 'https://www.eqxiu.com', pricing: 'free_paid', tags: ['H5', '页面', '营销'] },
  { name: 'MAKA', description: 'H5 设计工具', category: 'design', url: 'https://www.maka.im', pricing: 'free_paid', tags: ['H5', '设计', '营销'] },
  { name: '兔展', description: 'H5 制作平台', category: 'design', url: 'https://www.rabbitpre.com', pricing: 'free_paid', tags: ['H5', '制作', '企业'] },
  { name: '人人秀', description: 'H5 页面制作', category: 'design', url: 'https://www.rrxiu.net', pricing: 'free_paid', tags: ['H5', '互动', '营销'] },
  { name: '有赞', description: '电商和零售服务', category: 'design', url: 'https://www.youzan.com', pricing: 'paid', tags: ['电商', '零售', 'SaaS'] },
  { name: '微盟', description: '智慧商业服务', category: 'design', url: 'https://www.weimob.com', pricing: 'paid', tags: ['商业', 'SaaS', '微信'] },
  { name: '微店', description: '手机开店平台', category: 'design', url: 'https://www.weidian.com', pricing: 'free_paid', tags: ['开店', '电商', '移动'] },
  { name: '小鹅通', description: '知识付费工具', category: 'design', url: 'https://www.xiaoe-tech.com', pricing: 'paid', tags: ['知识付费', '教育', '直播'] },
  { name: '千聊', description: '知识付费平台', category: 'design', url: 'https://www.qlchat.com', pricing: 'free_paid', tags: ['知识付费', '直播', '社群'] },
  { name: '荔枝微课', description: '在线教育平台', category: 'design', url: 'https://www.lizhiweike.com', pricing: 'free_paid', tags: ['教育', '微课', '知识'] },
  { name: '知识星球', description: '知识社群工具', category: 'design', url: 'https://www.zsxq.com', pricing: 'paid', tags: ['社群', '知识', '付费'] },
  { name: '得到', description: '知识服务应用', category: 'design', url: 'https://www.igetget.com', pricing: 'paid', tags: ['知识', '课程', '听书'] },
  { name: '混沌学园', description: '商业教育平台', category: 'design', url: 'https://www.hundun.cn', pricing: 'paid', tags: ['商业', '教育', '创新'] },
  { name: '三节课', description: '在线职业教育', category: 'design', url: 'https://www.sanjieke.cn', pricing: 'paid', tags: ['职业教育', '互联网', '课程'] },
  { name: '极客时间', description: 'IT 知识付费', category: 'design', url: 'https://time.geekbang.org', pricing: 'paid', tags: ['IT', '技术', '课程'] },
  { name: '慕课网', description: 'IT 技能学习', category: 'design', url: 'https://www.imooc.com', pricing: 'free_paid', tags: ['IT', '视频', '实战'] },
  { name: '网易云课堂', description: '在线学习平台', category: 'design', url: 'https://study.163.com', pricing: 'free_paid', tags: ['学习', '课程', '平台'] },
  { name: '腾讯课堂', description: '在线职业教育', category: 'design', url: 'https://ke.qq.com', pricing: 'free_paid', tags: ['教育', '职业', '课程'] },
  { name: '学而思网校', description: 'K12 在线教育', category: 'design', url: 'https://www.xueersi.com', pricing: 'paid', tags: ['K12', '教育', '学科'] },
  { name: '猿辅导', description: '在线教育平台', category: 'design', url: 'https://www.yuanfudao.com', pricing: 'paid', tags: ['教育', '辅导', 'K12'] },
  { name: '作业帮', description: '在线教育平台', category: 'design', url: 'https://www.zybang.com', pricing: 'free_paid', tags: ['教育', '作业', '答疑'] },
  { name: '掌门1对1', description: '在线一对一辅导', category: 'design', url: 'https://www.zhangmen.com', pricing: 'paid', tags: ['一对一', '辅导', '教育'] },
  { name: 'VIPKID', description: '在线少儿英语', category: 'design', url: 'https://www.vipkid.com', pricing: 'paid', tags: ['英语', '少儿', '外教'] },
  { name: 'DaDa英语', description: '在线青少儿英语', category: 'design', url: 'https://www.dadaabc.com', pricing: 'paid', tags: ['英语', '青少儿', '外教'] },
  { name: '流利说', description: 'AI 英语学习', category: 'design', url: 'https://www.liulishuo.com', pricing: 'free_paid', tags: ['英语', 'AI', '口语'] },
  { name: '多邻国', description: '语言学习应用', category: 'design', url: 'https://www.duolingo.com', pricing: 'free_paid', tags: ['语言', '学习', '游戏'] },
  { name: '百词斩', description: '英语单词学习', category: 'design', url: 'https://www.baicizhan.com', pricing: 'free', tags: ['单词', '英语', '记忆'] },
  { name: '扇贝单词', description: '英语单词学习', category: 'design', url: 'https://www.shanbay.com', pricing: 'free_paid', tags: ['单词', '英语', '打卡'] },
  { name: '沪江开心词场', description: '多语言单词学习', category: 'design', url: 'https://www.hjenglish.com', pricing: 'free', tags: ['单词', '多语言', '闯关'] },
  { name: '墨墨背单词', description: '抗遗忘背单词', category: 'design', url: 'https://www.maimemo.com', pricing: 'free_paid', tags: ['单词', '记忆', '算法'] },
  { name: '欧路词典', description: '离线词典应用', category: 'design', url: 'https://www.eudic.net', pricing: 'free_paid', tags: ['词典', '离线', '翻译'] },
  { name: '有道词典', description: '在线翻译词典', category: 'design', url: 'https://dict.youdao.com', pricing: 'free', tags: ['词典', '翻译', '学习'] },
  { name: '金山词霸', description: '翻译学习工具', category: 'design', url: 'https://www.iciba.com', pricing: 'free', tags: ['词典', '翻译', '学习'] },
  { name: '百度翻译', description: '在线翻译服务', category: 'design', url: 'https://fanyi.baidu.com', pricing: 'free', tags: ['翻译', '在线', '百度'] },
  { name: '腾讯翻译君', description: 'AI 翻译工具', category: 'design', url: 'https://fanyi.qq.com', pricing: 'free', tags: ['翻译', 'AI', '腾讯'] },
  { name: '阿里翻译', description: '电商翻译服务', category: 'design', url: 'https://translate.alibaba.com', pricing: 'free', tags: ['翻译', '电商', '阿里'] },
  { name: '搜狗翻译', description: '在线翻译工具', category: 'design', url: 'https://fanyi.sogou.com', pricing: 'free', tags: ['翻译', '在线', '搜狗'] },
  { name: '彩云小译', description: 'AI 翻译工具', category: 'design', url: 'https://fanyi.caiyunapp.com', pricing: 'free_paid', tags: ['翻译', 'AI', '文档'] },
];


async function main() {
  console.log('🚀 开始导入 AI 工具...\n');
  
  let successCount = 0;
  let skipCount = 0;
  let errorCount = 0;
  
  // 获取所有分类
  const categories = await prisma.category.findMany();
  const categoryMapByName = new Map(categories.map(c => [c.name, c.id]));
  
  console.log(`📊 数据库中有 ${categories.length} 个分类`);
  console.log(`📦 准备导入 ${mockTools.length} 个工具\n`);
  
  for (const tool of mockTools) {
    try {
      const categoryName = categoryMap[tool.category] || '其他工具';
      const categoryId = categoryMapByName.get(categoryName);
      
      if (!categoryId) {
        console.log(`⚠️  跳过: ${tool.name} - 分类 "${categoryName}" 不存在`);
        skipCount++;
        continue;
      }
      
      // 检查是否已存在
      const existing = await prisma.tool.findFirst({
        where: {
          OR: [
            { name: tool.name },
            { websiteUrl: tool.url },
          ],
        },
      });
      
      if (existing) {
        console.log(`⏭️  跳过: ${tool.name} - 已存在`);
        skipCount++;
        continue;
      }
      
      // 创建工具
      const slug = slugify(tool.name);
      await prisma.tool.create({
        data: {
          name: tool.name,
          slug,
          description: tool.description,
          shortDesc: tool.description,
          websiteUrl: tool.url,
          categoryId,
          pricingType: tool.pricing === 'free' ? 'FREE' : tool.pricing === 'paid' ? 'PAID' : 'FREEMIUM',
          tags: tool.tags.join(','),
          isActive: true,
          status: 'approved',
          isFeatured: Math.random() > 0.8, // 20% 设为推荐
          viewCount: Math.floor(Math.random() * 1000),
        },
      });
      
      console.log(`✅ 导入: ${tool.name} (${categoryName})`);
      successCount++;
    } catch (error) {
      console.error(`❌ 错误: ${tool.name} -`, error);
      errorCount++;
    }
  }
  
  console.log('\n📈 导入完成!');
  console.log(`   成功: ${successCount}`);
  console.log(`   跳过: ${skipCount}`);
  console.log(`   错误: ${errorCount}`);
  
  await prisma.$disconnect();
}

main().catch(console.error);
