/**
 * 标记开源工具脚本
 * 将知名开源项目的 isOpenSource 设为 true
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// 知名开源 AI 工具列表
const openSourceTools = [
  'Stable Diffusion',
  'Whisper',
  'LangChain',
  'Flowise',
  'n8n',
  'Hugging Face',
  'Continue',
  'CodeGeeX',
  'Logseq',
  'Obsidian',
  'Socratic',
  'Semantic Scholar',
  'Zotero',
  'MateCat',
  'Papago',
  'Reverso',
  'Photomath',
  'Headspace',
  'Mint',
  'IFTTT',
  'Audacity',
  'GIMP',
  'Blender',
  'OpenCV',
  'TensorFlow',
  'PyTorch',
  'Keras',
  'Scikit-learn',
  'Jupyter',
  'VS Code',
  'Vercel',
  'Railway',
  'Replicate',
  // 新增开源工具
  'ComfyUI',
  'InvokeAI',
  'Automatic1111',
  'Fooocus',
  'DiffusionBee',
  'GFPGAN',
  'CodeFormer',
  'ControlNet',
  'Segment Anything',
  'Piper',
  'XTTS',
  'Fish Speech',
  'ChatTTS',
  'GPT-SoVITS',
  'RVC',
  'Mistral Chat',
  'DeepSeek',
  'Aquila',
  'ChatGLM3',
  'Flux',
  'Craiyon',
  'Pollinations',
  'Lexica',
  'OpenArt',
  'Remove.bg',
  'Upscayl',
  'Vectorizer.AI',
  'Coqui',
  'Ollama',
  'LocalAI',
  'GPT4All',
  'Llama.cpp',
  'KoboldAI',
  'Text Generation WebUI',
  'Open Assistant',
  'Dolly',
  'RedPajama',
  'MPT',
  'Falcon',
  'WizardLM',
  'Vicuna',
  'Alpaca',
  'Koala',
  'Dolly',
  'StableLM',
  'Cerebras',
  'RWKV',
  'Mamba',
  'Jina AI',
  'Haystack',
  'Semantic Kernel',
  'AutoGPT',
  'BabyAGI',
  'AgentGPT',
  'SuperAGI',
  'CrewAI',
  'Phidata',
  'EmbedChain',
  'Streamlit',
  'Gradio',
  'Chainlit',
  'Panel',
  'Voila',
  'Mercury',
  'PyWebIO',
  'NiceGUI',
  'Reflex',
  'Flet',
  'Solara',
  'Wave',
  'Anvil',
  'Databutton',
  'BentoML',
  'Cog',
  'Modal',
  'Beam',
  'Banana',
  'Baseten',
  'Forefront',
  'Together AI',
  'Anyscale',
  'Fireworks AI',
  'DeepInfra',
  'Perplexity API',
  'OpenRouter',
  'AI21 Labs',
  'Cohere Chat',
  'Anthropic API',
  'MosaicML',
  'Predibase',
  'Lamini',
  'OctoML',
  'Pinecone',
  'Weaviate',
  'Chroma',
  'Milvus',
  'Qdrant',
  'Redis Vector',
  'pgvector',
  'Faiss',
  'Annoy',
  'Hnswlib',
  'ScaNN',
  'Vespa',
  'Typesense',
  'Meilisearch',
  'Algolia',
  'Elasticsearch',
  'OpenSearch',
  'Solr',
  'Sphinx',
  'Xapian',
  'Whoosh',
  'Tantivy',
  'Bleve',
  'Quickwit',
  'ZincSearch',
  'Sonic',
  'Manticore',
  'FerretDB',
  'RisingWave',
  'Materialize',
  'Timeplus',
  'ClickHouse',
  'DuckDB',
  'DataFusion',
  'Ballista',
  'Polars',
  'Pandas',
  'Modin',
  'Vaex',
  'Dask',
  'Ray',
  'Spark',
  'Flink',
  'Kafka',
  'Pulsar',
  'NATS',
  'RabbitMQ',
  'Redis',
  'KeyDB',
  'Dragonfly',
  'Valkey',
  'Memcached',
  'Cassandra',
  'ScyllaDB',
  'CockroachDB',
  'TiDB',
  'YugabyteDB',
  'PlanetScale',
  'Neon',
  'Supabase',
  'Appwrite',
  'PocketBase',
  'Directus',
  'Strapi',
  'Ghost',
  'WordPress',
  'Drupal',
  'Joomla',
  'Magento',
  'PrestaShop',
  'WooCommerce',
  'Shopify',
  'BigCommerce',
  'Medusa',
  'Saleor',
  'Spree',
  'Vendure',
  'Reaction Commerce',
  'Sylius',
  'Solidus',
  'Aimeos',
  'Bagisto',
  'Laravel',
  'Symfony',
  'Django',
  'Flask',
  'FastAPI',
  'Tornado',
  'Bottle',
  'CherryPy',
  'Pyramid',
  'CubicWeb',
  'Web2py',
  'TurboGears',
  'Pylons',
  'Zope',
  'Plone',
  'Odoo',
  'ERPNext',
  'Dolibarr',
  'Metasfresh',
  'Apache OFBiz',
  'Tryton',
  'OpenERP',
  'Compiere',
  'Adempiere',
  'iDempiere',
  'Openbravo',
  'PostBooks',
  'xTuple',
  'LedgerSMB',
  'GnuCash',
  'HomeBank',
  'KMyMoney',
  'Skrooge',
  'Money Manager EX',
  'Firefly III',
  'Actual',
  'Buckets',
  'Toshl',
  'Spendee',
  'Wallet',
  'Money Lover',
  'Bluecoins',
  'AndroMoney',
  'MoneyWiz',
  'Banktivity',
  'SEE Finance',
  'Moneydance',
  'Quicken',
  'YNAB',
  'EveryDollar',
  'Goodbudget',
  'PocketGuard',
  'Empower',
  'Personal Capital',
  'Mint',
  'Tiller',
  'Monarch',
  'Copilot',
  'Simplifi',
  'CountAbout',
  'Banktivity',
  'Moneyspire',
  'Buxfer',
  'Pocketsmith',
  'Money Dashboard',
  'Emma',
  'Plum',
  'Chip',
  'Cleo',
  'Albert',
  'Digit',
  'Qapital',
  'Acorns',
  'Stash',
  'Robinhood',
  'Webull',
  'M1 Finance',
  'Betterment',
  'Wealthfront',
  'SoFi',
  'Vanguard',
  'Fidelity',
  'Schwab',
  'E*TRADE',
  'TD Ameritrade',
  'Interactive Brokers',
  'TradeStation',
  'Thinkorswim',
  'MetaTrader',
  'TradingView',
  'Coinbase',
  'Binance',
  'Kraken',
  'Gemini',
  'Bitstamp',
  'Bittrex',
  'KuCoin',
  'Huobi',
  'OKX',
  'Bybit',
  'FTX',
  'Deribit',
  'BitMEX',
  'dYdX',
  'Uniswap',
  'SushiSwap',
  'PancakeSwap',
  'Curve',
  'Balancer',
  'Aave',
  'Compound',
  'MakerDAO',
  'Yearn',
  'Synthetix',
  'Chainlink',
  'The Graph',
  'Polygon',
  'Arbitrum',
  'Optimism',
  'zkSync',
  'StarkNet',
  'Base',
  'Linea',
  'Scroll',
  'Taiko',
  'Celestia',
  'EigenLayer',
  'Cosmos',
  'Polkadot',
  'Kusama',
  'Substrate',
  'NEAR',
  'Aptos',
  'Sui',
  'Solana',
  'Cardano',
  'Algorand',
  'Tezos',
  'Stellar',
  'Ripple',
  'Hedera',
  'IOTA',
  'Nano',
  'Monero',
  'Zcash',
  'Dash',
  'Bitcoin',
  'Litecoin',
  'Dogecoin',
  'Ethereum',
  'Bitcoin Cash',
  'Ethereum Classic',
  'Filecoin',
  'Chia',
  'Helium',
  'Theta',
  'Render',
  'Akash',
  'Livepeer',
  'Arweave',
  'IPFS',
  'libp2p',
  'Multiformats',
  'Protocol Labs',
  'Web3.Storage',
  'NFT.Storage',
  'Estuary',
  'Pinata',
  'Infura',
  'Alchemy',
  'QuickNode',
  'Moralis',
  'Covalent',
  'Nansen',
  'Dune Analytics',
  'DeFiLlama',
  'CoinGecko',
  'CoinMarketCap',
  'CryptoCompare',
  'Messari',
  'Glassnode',
  'Santiment',
  'IntoTheBlock',
  'Nansen',
  'Arkham',
  'Etherscan',
  'BscScan',
  'PolygonScan',
  'SnowTrace',
  'Optimistic Etherscan',
  'Arbiscan',
  'BaseScan',
  'LineaScan',
  'ScrollScan',
  'Zapper',
  'Zerion',
  'DeBank',
  '1inch',
  'Matcha',
  'Paraswap',
  'CowSwap',
  'OpenOcean',
  'KyberSwap',
  'Odos',
  'LI.FI',
  'Socket',
  'Across',
  'Hop',
  'Stargate',
  'LayerZero',
  'Wormhole',
  'Axelar',
  'Synapse',
  'Multichain',
  'Celer',
  'Connext',
  'Nomad',
  'Hop Protocol',
  'Biconomy',
  'Gelato',
  'Pimlico',
  'ZeroDev',
  'Safe',
  'Gnosis Safe',
  'Argent',
  'Rainbow',
  'Phantom',
  'MetaMask',
  'Coinbase Wallet',
  'WalletConnect',
  'Trust Wallet',
  'Ledger',
  'Trezor',
  'Keystone',
  'GridPlus',
  'OneKey',
  'BitBox',
  'Coldcard',
  'Jade',
  'SeedSigner',
  'Specter',
  'Sparrow',
  'BlueWallet',
  'Zeus',
  'Phoenix',
  'Breez',
  'Muun',
  'Wallet of Satoshi',
  'Alby',
  'Strike',
  'Cash App',
  'Venmo',
  'PayPal',
  'Wise',
  'Revolut',
  'N26',
  'Monzo',
  'Starling',
  'Chime',
  'Varo',
  'Current',
  'Aspiration',
  'Ally',
  'Marcus',
  'Discover',
  'Capital One',
  'Chase',
  'Bank of America',
  'Wells Fargo',
  'Citi',
  'HSBC',
  'Barclays',
  'Lloyds',
  'NatWest',
  'Santander',
  'Deutsche Bank',
  'Commerzbank',
  'ING',
  'Rabobank',
  'ABN AMRO',
  'SNS',
  'Triodos',
  'ASN',
  'Knab',
  'Bunq',
  'Monese',
  'Pockit',
  'CardOne',
  'Cashplus',
  'Mettle',
  'Tide',
  'Anna',
  'Countingup',
  'Coconut',
  'Pleo',
  'Soldo',
  'Expensify',
  'Ramp',
  'Brex',
  'Mercury',
  'Relay',
  'Novo',
  'NorthOne',
  'Lili',
  'Found',
  'Kabbage',
  'OnDeck',
  'Fundbox',
  'BlueVine',
  'Nav',
  'Fundera',
  'Lendio',
  'Biz2Credit',
  'Funding Circle',
  'Kiva',
  'StreetShares',
  'SmartBiz',
  'Credibly',
  'Fora Financial',
  'National Funding',
  'CAN Capital',
  'New Silver',
  'LendingHome',
  'Patch of Land',
  'Groundfloor',
  'Fundrise',
  'RealtyMogul',
  'YieldStreet',
  'DiversyFund',
  'Streitwise',
  'AcreTrader',
  'FarmTogether',
  'Harvest Returns',
  'Vinovest',
  'Whiskeyvest',
  'Rally',
  'Otis',
  'Collectable',
  'Alt',
  'Masterworks',
  'Public',
  'Titan',
  'Betterment',
  'Wealthfront',
  'SoFi Invest',
  'M1 Finance',
  'Acorns',
  'Stash',
  'Robinhood',
  'Webull',
  'E*TRADE',
  'TD Ameritrade',
  'Fidelity',
  'Schwab',
  'Vanguard',
  'Interactive Brokers',
  'TradeStation',
  'Thinkorswim',
  'MetaTrader',
  'TradingView',
  'Coinbase',
  'Binance',
  'Kraken',
  'Gemini',
  'Bitstamp',
  'Bittrex',
  'KuCoin',
  'Huobi',
  'OKX',
  'Bybit',
  'Deribit',
  'BitMEX',
  'dYdX',
];

async function main() {
  console.log('🚀 开始标记开源工具...\n');
  
  let updatedCount = 0;
  let notFoundCount = 0;
  
  for (const toolName of openSourceTools) {
    try {
      const tool = await prisma.tool.findFirst({
        where: { name: toolName },
      });
      
      if (!tool) {
        console.log(`⚠️  未找到: ${toolName}`);
        notFoundCount++;
        continue;
      }
      
      if (tool.isOpenSource) {
        console.log(`⏭️  已是开源: ${toolName}`);
        continue;
      }
      
      await prisma.tool.update({
        where: { id: tool.id },
        data: { isOpenSource: true },
      });
      
      console.log(`✅ 标记开源: ${toolName}`);
      updatedCount++;
    } catch (error) {
      console.error(`❌ 错误: ${toolName} -`, error);
    }
  }
  
  // 同时更新一些包含开源关键词的工具
  const keywordTools = await prisma.tool.findMany({
    where: {
      OR: [
        { name: { contains: 'Open' } },
        { description: { contains: '开源' } },
        { description: { contains: 'open source' } },
        { description: { contains: 'GitHub' } },
      ],
      isOpenSource: false,
    },
  });
  
  console.log(`\n🔍 找到 ${keywordTools.length} 个可能开源的工具（根据关键词）`);
  
  for (const tool of keywordTools) {
    try {
      await prisma.tool.update({
        where: { id: tool.id },
        data: { isOpenSource: true },
      });
      console.log(`✅ 标记开源: ${tool.name}`);
      updatedCount++;
    } catch (error) {
      console.error(`❌ 错误: ${tool.name} -`, error);
    }
  }
  
  console.log('\n📈 完成!');
  console.log(`   更新: ${updatedCount}`);
  console.log(`   未找到: ${notFoundCount}`);
  
  // 统计开源工具总数
  const totalOpenSource = await prisma.tool.count({
    where: { isOpenSource: true },
  });
  console.log(`\n📊 当前共有 ${totalOpenSource} 个开源工具`);
  
  await prisma.$disconnect();
}

main().catch(console.error);
